import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Lang = "en" | "ar" | "fr" | "es" | "de" | "pt" | "it" | "tr";

export const LANG_LIST: { code: Lang; label: string; dir: "ltr" | "rtl"; iso: string }[] = [
  { code: "en", label: "English",    dir: "ltr", iso: "EN" },
  { code: "ar", label: "العربية",    dir: "rtl", iso: "AR" },
  { code: "fr", label: "Français",   dir: "ltr", iso: "FR" },
  { code: "es", label: "Español",    dir: "ltr", iso: "ES" },
  { code: "de", label: "Deutsch",    dir: "ltr", iso: "DE" },
  { code: "pt", label: "Português",  dir: "ltr", iso: "PT" },
  { code: "it", label: "Italiano",   dir: "ltr", iso: "IT" },
  { code: "tr", label: "Türkçe",     dir: "ltr", iso: "TR" },
];

const T = {
  en: {
    status:"Status", calls:"Calls", communities:"Communities", chats:"Chats", profile:"Profile",
    statusTitle:"Status", statusSub:"Share moments that disappear in 24 hours.",
    myStatus:"My status", tapToAdd:"Tap to add status update",
    recentUpdates:"Recent updates", noUpdates:"No recent updates",
    noUpdatesDesc:"Status updates from other people will appear here.",
    removeStatus:"Remove my status", newStatus:"New status",
    whatsOnMind:"What's on your mind?", share:"Share",
    disappears:"Disappears in 24h", addImage:"Add image", addText:"Add text", preview:"Preview",
    language:"Language",
    welcome:"Welcome to Chatrazze",
    welcomeSub:"Select a conversation or start a new one to message anyone in real time.",
    notifEnabled:"Notifications enabled ✓",
    notifBlocked:"Notifications blocked — change in browser settings",
    notifNotSupported:"Notifications not supported in this browser",
    notifActive:"Enabled — tap to test",
    notifDenied:"Blocked — change in browser settings",
    notifPrompt:"Tap to allow notifications",
    browserNotif:"Browser notifications",
    notifSound:"Notification sound",
    notifPreview:"Show message preview",
    notifPreviewDesc:"Display the message text in the notification",
    ringtoneLabel:"Notification ringtone", ringtoneTap:"Tap to preview",
    newMessage:"New message",
    statusPosted:"Status posted — visible for 24 hours", statusRemoved:"Status removed",
    callEnded:"Call ended", missedCall:"Missed call", missedCallFrom:"Missed call from", callNotAnswered:"Call not answered",
    sentPhoto:"Sent a photo", sentVideo:"Sent a video", sentVoice:"Sent a voice message", sentFile:"Sent a file",
    postedNewStatus:"Posted a new status", unreadMessage:"unread message", unreadMessages:"unread messages",
    darkTheme:"Dark theme", currently:"Currently",
    enterSend:"Press Enter to send", enterSendDesc:"Otherwise Enter inserts a new line",
    autoplay:"Autoplay video messages",
    showOnline:"Show online status", showOnlineDesc:"Let others see when you're online",
    showLastSeen:"Show last seen", showLastSeenDesc:"Display when you were last active",
    readReceipts:"Read receipts", readReceiptsDesc:"Show double check marks when you read messages",
    privacyNote:"Privacy preferences are stored on this device.",
    browserStorage:"Browser storage", clearCache:"Clear local cache",
    clearCacheDesc:"Removes themes and local settings",
    storageNote:"Messages stay safe in the cloud — only local preferences are cleared.",
    used:"used of", available:"available",
    image:"Image", video:"Video", file:"File / PDF",
    typeMessage:"Type a message",
    today:"Today", yesterday:"Yesterday",
    online:"online", typing:"typing...", lastSeen:"last seen",
    justNow:"just now", minAgo:"m ago", hAgo:"h ago",
    noMessages:"No messages yet — say hello!",
    sendImage:"Send image", sendVideo:"Send video", sendFile:"Send file",
    uploading:"Uploading", uploadFailed:"Upload failed",
    voiceMessage:"Voice message", stopRecording:"Stop recording",
    slideToCancel:"Slide to cancel",
    micDenied:"Microphone access denied.",
    switchToLight:"Switch to light", switchToDark:"Switch to dark",
    lightTheme:"Light theme", lightThemeOn:"Light theme on", darkThemeOn:"Dark theme on",
    profileTitle:"Profile",
    accountSetting:"Account", privacySetting:"Privacy",
    privacySettingSub:"Online status, last seen, read receipts",
    chatsSetting:"Chats", chatsSettingSub:"Theme, send key, autoplay",
    notificationsSetting:"Notifications", notificationsSettingSub:"Browser alerts, sound, preview",
    storageDataSetting:"Storage & data", storageDataSub:"Browser storage, clear cache",
    tapToCopyId:"Tap to copy your unique ID", userIdCopied:"User ID copied",
    logOut:"Log out",
    profilePhotoUpdated:"Profile photo updated", couldNotUploadPhoto:"Could not upload photo",
    profileSaved:"Profile saved", couldNotSaveProfile:"Could not save profile",
    pleasePickImage:"Please pick an image file", imageTooLarge:"Image must be under 5 MB",
    save:"Save", saving:"Saving...", defaultBio:"Hey there! I'm using Chatrazze.",
    recentCallHistory:"Recent call history.",
    noCallsYet:"No calls yet",
    noCallsDesc:"Voice and video calls will appear here after you make or receive a call.",
    callTypesLabel:"Call types", incoming:"Incoming", outgoing:"Outgoing", missed:"Missed",
    callHistoryCleared:"Call history cleared", dAgo:"d ago",
    newChat:"New Chat", newGroup:"New Group",
    searchChatsMessages:"Search chats and messages",
    filterAll:"All", filterUnread:"Unread", filterFavorites:"Favorites", filterGroups:"Groups",
    noChatsFilter:"No chats match your filter.", noChatsYet:"No chats yet. Tap + to start one.",
    sayHi:"Say hi", removeFavorite:"Remove favorite", markFavorite:"Mark favorite",
    searchByNameOrId:"Search by name or User ID",
    searching:"Searching...", noUsersFound:"No users found.",
    groupNameLabel:"Group name", enterGroupName:"Enter group name...",
    addMembersLabel:"Add members", searchUsersPlaceholder:"Search users...",
    creating:"Creating…", createGroupBtn:"Create Group",
    groupInfo:"Group Info", membersCount:"members",
    messagesLabel:"Messages", photosLabel:"Photos", videosLabel:"Videos",
    voiceLabel:"Voice", filesLabel:"Files",
    addMember:"Add Member", loadingMembers:"Loading members...",
    youSuffix:"(You)", onlineCapital:"Online", offlineCapital:"Offline",
    noMediaShared:"No media shared yet.", noFilesShared:"No files shared yet.",
    leaveGroup:"Leave Group", leavingGroup:"Leaving...", leftGroup:"You left the group.",
    searchByName:"Search by name...",
    moreActions:"More Actions", viewAllMembers:"View all members", showLessMembers:"Show less",
    typeNameToFind:"Type a name to find someone to add.",
    notInGroup:"No users found — or they're already in the group.",
    adding:"Adding…", add:"Add",
    contactInfo:"Contact Info", emailLabel:"Email", phoneLabel:"Phone",
    voiceMessagesLabel:"Voice Messages", voiceMessagesCount:"voice messages",
    voiceCallBtn:"Voice", videoCallBtn:"Video",
    mediaTab:"Media", filesTab:"Files",
    unblockUser:"Unblock", blockUser:"Block",
    viewProfile:"View profile", sharedMedia:"Shared media", sharedFiles:"Shared files",
    clearChat:"Clear chat", confirmBlock:"Block this user?", confirmClear:"Clear this chat?",
    cancel:"Cancel", confirm:"Confirm",
    privacyPanelTitle:"Privacy", storagePanelTitle:"Storage",
    clearedCacheMsg:"cached items cleared", couldNotClearCache:"Could not clear cache",
    fastModernMessaging:"Fast, modern messaging.",
    signIn:"Sign in", signUp:"Sign up",
    displayNamePlaceholder:"Display name", phoneOptionalPlaceholder:"Phone (optional)",
    emailPlaceholder:"Email", passwordPlaceholder:"Password",
    pleaseWait:"Please wait...", createAccount:"Create account",
    poweredBy:"Powered by Supabase. Your messages are stored in real time.",
    authFailed:"Authentication failed",
    callBack:"Call back",
    callingLabel:"Calling...", connectingLabel:"Connecting...",
    incomingVideoCall:"Incoming video call", incomingVoiceCall:"Incoming voice call",
    declineBtn:"Decline", acceptBtn:"Accept",
    speakerBtn:"Speaker", muteBtn:"Mute", unmuteBtn:"Unmute",
    endBtn:"End", cameraBtn:"Camera",
    loadingDots:"Loading...", members:"members", group:"Group",
    addedToGroup:"added to the group!",
    chatBgTitle:"Chat Background", chatBgDesc:"Choose your chat wallpaper",
    adminLabel:"Admin", editGroup:"Edit Group", groupPhoto:"Group Photo",
    groupNameEdited:"Group name updated", groupPhotoUpdated:"Group photo updated",
    addCaption:"Add caption...", storyText:"Text", storyCamera:"Photo", tapCameraToUpload:"Tap to upload photo",
    groupDescription:"Group description", addGroupDesc:"Add description", editDescription:"Edit description", descriptionHint:"About the group...",
    inviteViaLink:"Invite via link", qrCode:"QR code", copyLink:"Copy link", linkCopied:"Link copied!",
    disappearingMsgs:"Disappearing messages", disappearOff:"Off", disappear24h:"24 hours", disappear7d:"7 days", disappear90d:"90 days",
    lockChat:"Lock chat", lockChatDesc:"Require PIN to open", setPIN:"Set PIN", enterPIN:"Enter PIN",
    confirmPIN:"Confirm PIN", pinSet:"PIN set", pinRemoved:"PIN removed", wrongPIN:"Wrong PIN",
    muteNotifs:"Mute notifications", mute8h:"8 hours", mute1w:"1 week", muteAlways:"Always",
    unmute:"Unmute", mutedLabel:"Muted",
    encryptionInfo:"Encryption", encryptTitle:"End-to-end encrypted",
    encryptDesc:"Messages and calls in this chat are secured with end-to-end encryption.",
    exportChat:"Export chat", chatExported:"Chat exported",
    clearAllMsgs:"Clear all messages", chatCleared:"Chat cleared",
    reportGroup:"Report group", reportSent:"Report sent",
    noResults:"No results", callMember:"Call member",
    searchInChat:"Search in chat",
    settingsSection:"Settings", accountSection:"Account", appearanceSection:"Appearance", helpSection:"Help",
    inviteFriends:"Invite friends", starredMessages:"Starred messages", starredMessagesSub:"Chats you've starred",
    broadcastMsg:"Broadcast message", broadcastMsgSub:"Send to multiple people at once",
    linkedDevicesLabel:"Linked devices", linkedDevicesSub:"Active sessions on your account",
    helpFeedback:"Help & Feedback", helpFeedbackSub:"Contact support or send feedback",
    shareBtn:"Share", inviteShareDesc:"Share the link with your friends to connect on Chatrazze",
    shareLink:"Share", noStarredChats:"No starred chats", noStarredChatsSub:"Long-press a chat in the list to star it",
    searchUserPlaceholder:"Search for a user…", nextBtn:"Next", selectedCount:"selected",
    typeYourMessage:"Write your message…", goBack:"Back", personCount:"people",
    sentToPrefix:"Message sent to", couldNotSend:"Could not send",
    activeSession:"Currently active session on this device", thisDeviceActive:"This device · Active",
    lastActivity:"Last activity:", devicesNote:"Chatrazze supports one session at a time. Sign in from any browser and your session syncs automatically via Supabase.",
    bioLabel:"Bio", nameLabel:"Name", linksLabel:"Links", addLinkBtn:"Add a link",
    editBtn:"Edit", unknownBrowser:"Unknown browser", unknownOS:"Unknown OS",
    reply:"Reply", copyText:"Copy text", deleteMsg:"Delete", replyingTo:"Replying to",
    msgCopied:"Copied!", you:"You", forwardMsg:"Forward",
  },
  ar: {
    status:"الحالة", calls:"المكالمات", communities:"المجموعات", chats:"المحادثات", profile:"الملف الشخصي",
    statusTitle:"الحالة", statusSub:"شارك لحظاتك التي تختفي خلال 24 ساعة.",
    myStatus:"حالتي", tapToAdd:"اضغط لإضافة تحديث",
    recentUpdates:"التحديثات الأخيرة", noUpdates:"لا توجد تحديثات",
    noUpdatesDesc:"ستظهر هنا تحديثات الحالة من الأشخاص الآخرين.",
    removeStatus:"حذف حالتي", newStatus:"حالة جديدة",
    whatsOnMind:"ماذا يدور في ذهنك؟", share:"مشاركة",
    disappears:"تختفي خلال 24 ساعة", addImage:"إضافة صورة", addText:"إضافة نص", preview:"معاينة",
    language:"اللغة",
    welcome:"مرحباً بك في Chatrazze",
    welcomeSub:"اختر محادثة أو ابدأ محادثة جديدة للتواصل في الوقت الفعلي.",
    notifEnabled:"تم تفعيل الإشعارات ✓",
    notifBlocked:"تم حظر الإشعارات — غيّر الإعدادات في المتصفح",
    notifNotSupported:"الإشعارات غير مدعومة في هذا المتصفح",
    notifActive:"مفعّل — اضغط للاختبار",
    notifDenied:"محظور — غيّر الإعدادات في المتصفح",
    notifPrompt:"اضغط للسماح بالإشعارات",
    browserNotif:"إشعارات المتصفح",
    notifSound:"صوت الإشعار",
    notifPreview:"عرض معاينة الرسالة",
    notifPreviewDesc:"عرض نص الرسالة في الإشعار",
    ringtoneLabel:"رنة الإشعار", ringtoneTap:"اضغط للمعاينة",
    newMessage:"رسالة جديدة",
    statusPosted:"تم نشر الحالة — تظهر لمدة 24 ساعة", statusRemoved:"تم حذف الحالة",
    callEnded:"انتهى الاتصال", missedCall:"مكالمة فائتة", missedCallFrom:"مكالمة فائتة من", callNotAnswered:"لم يتم الرد على المكالمة",
    sentPhoto:"أرسل صورة", sentVideo:"أرسل فيديو", sentVoice:"أرسل رسالة صوتية", sentFile:"أرسل ملفا",
    postedNewStatus:"نشر حالة جديدة", unreadMessage:"رسالة غير مقروءة", unreadMessages:"رسائل غير مقروءة",
    darkTheme:"الوضع الداكن", currently:"حالياً",
    enterSend:"Enter للإرسال", enterSendDesc:"وإلا فإن Enter يضيف سطراً جديداً",
    autoplay:"تشغيل الفيديو تلقائياً",
    showOnline:"إظهار حالة الاتصال", showOnlineDesc:"السماح للآخرين برؤية حالتك",
    showLastSeen:"إظهار آخر ظهور", showLastSeenDesc:"عرض وقت آخر نشاط لك",
    readReceipts:"علامات القراءة", readReceiptsDesc:"إظهار علامة مزدوجة عند قراءة الرسائل",
    privacyNote:"تُحفظ إعدادات الخصوصية على هذا الجهاز.",
    browserStorage:"تخزين المتصفح", clearCache:"مسح الذاكرة المؤقتة",
    clearCacheDesc:"يزيل السمات والإعدادات المحلية",
    storageNote:"تبقى الرسائل آمنة في السحابة — يُمسح فقط التفضيلات المحلية.",
    used:"مستخدم من", available:"متاح",
    image:"صورة", video:"فيديو", file:"ملف / PDF",
    typeMessage:"اكتب رسالة",
    today:"اليوم", yesterday:"أمس",
    online:"متصل", typing:"يكتب...", lastSeen:"آخر ظهور",
    justNow:"الآن", minAgo:"د", hAgo:"س",
    noMessages:"لا توجد رسائل بعد — قل مرحباً!",
    sendImage:"إرسال صورة", sendVideo:"إرسال فيديو", sendFile:"إرسال ملف",
    uploading:"جارٍ الرفع", uploadFailed:"فشل الرفع",
    voiceMessage:"رسالة صوتية", stopRecording:"إيقاف التسجيل",
    slideToCancel:"اسحب للإلغاء",
    micDenied:"تم رفض الوصول إلى الميكروفون.",
    switchToLight:"التبديل إلى الفاتح", switchToDark:"التبديل إلى الداكن",
    lightTheme:"المظهر الفاتح", lightThemeOn:"تم تفعيل المظهر الفاتح", darkThemeOn:"تم تفعيل المظهر الداكن",
    profileTitle:"الملف الشخصي",
    accountSetting:"الحساب", privacySetting:"الخصوصية",
    privacySettingSub:"حالة الاتصال، آخر ظهور، علامات القراءة",
    chatsSetting:"المحادثات", chatsSettingSub:"المظهر، مفتاح الإرسال، التشغيل التلقائي",
    notificationsSetting:"الإشعارات", notificationsSettingSub:"تنبيهات المتصفح، الصوت، المعاينة",
    storageDataSetting:"التخزين والبيانات", storageDataSub:"تخزين المتصفح، مسح الذاكرة",
    tapToCopyId:"اضغط لنسخ معرّفك الفريد", userIdCopied:"تم نسخ معرّف المستخدم",
    logOut:"تسجيل الخروج",
    profilePhotoUpdated:"تم تحديث صورة الملف الشخصي", couldNotUploadPhoto:"تعذّر رفع الصورة",
    profileSaved:"تم حفظ الملف الشخصي", couldNotSaveProfile:"تعذّر حفظ الملف الشخصي",
    pleasePickImage:"يرجى اختيار ملف صورة", imageTooLarge:"يجب أن يكون حجم الصورة أقل من 5 ميغابايت",
    save:"حفظ", saving:"جارٍ الحفظ...", defaultBio:"مرحباً! أنا أستخدم Chatrazze.",
    recentCallHistory:"سجل المكالمات الأخيرة.",
    noCallsYet:"لا توجد مكالمات بعد",
    noCallsDesc:"ستظهر هنا مكالمات الصوت والفيديو بعد إجراء أو استقبال مكالمة.",
    callTypesLabel:"أنواع المكالمات", incoming:"واردة", outgoing:"صادرة", missed:"فائتة",
    callHistoryCleared:"تم مسح سجل المكالمات", dAgo:"ي",
    newChat:"محادثة جديدة", newGroup:"مجموعة جديدة",
    searchChatsMessages:"البحث في المحادثات والرسائل",
    filterAll:"الكل", filterUnread:"غير مقروء", filterFavorites:"المفضلة", filterGroups:"المجموعات",
    noChatsFilter:"لا توجد محادثات تطابق الفلتر.", noChatsYet:"لا توجد محادثات. اضغط + للبدء.",
    sayHi:"قل مرحباً", removeFavorite:"إزالة من المفضلة", markFavorite:"إضافة للمفضلة",
    searchByNameOrId:"البحث بالاسم أو معرّف المستخدم",
    searching:"جارٍ البحث...", noUsersFound:"لا يوجد مستخدمون.",
    groupNameLabel:"اسم المجموعة", enterGroupName:"أدخل اسم المجموعة...",
    addMembersLabel:"إضافة أعضاء", searchUsersPlaceholder:"البحث عن مستخدمين...",
    creating:"جارٍ الإنشاء…", createGroupBtn:"إنشاء المجموعة",
    groupInfo:"معلومات المجموعة", membersCount:"أعضاء",
    messagesLabel:"رسائل", photosLabel:"صور", videosLabel:"مقاطع",
    voiceLabel:"صوتية", filesLabel:"ملفات",
    addMember:"إضافة عضو", loadingMembers:"جارٍ تحميل الأعضاء...",
    youSuffix:"(أنت)", onlineCapital:"متصل", offlineCapital:"غير متصل",
    noMediaShared:"لا توجد وسائط مشتركة بعد.", noFilesShared:"لا توجد ملفات مشتركة بعد.",
    leaveGroup:"مغادرة المجموعة", leavingGroup:"جارٍ المغادرة...", leftGroup:"غادرت المجموعة.",
    searchByName:"البحث بالاسم...",
    moreActions:"المزيد من الإجراءات", viewAllMembers:"عرض كل الأعضاء", showLessMembers:"عرض أقل",
    typeNameToFind:"اكتب اسمًا للعثور على شخص لإضافته.",
    notInGroup:"لا يوجد مستخدمون — أو ربما هم أعضاء بالفعل.",
    adding:"جارٍ الإضافة…", add:"إضافة",
    contactInfo:"معلومات جهة الاتصال", emailLabel:"البريد الإلكتروني", phoneLabel:"الهاتف",
    voiceMessagesLabel:"رسائل صوتية", voiceMessagesCount:"رسائل صوتية",
    voiceCallBtn:"صوت", videoCallBtn:"فيديو",
    mediaTab:"وسائط", filesTab:"ملفات",
    unblockUser:"إلغاء الحظر", blockUser:"حظر",
    viewProfile:"عرض الملف", sharedMedia:"وسائط مشتركة", sharedFiles:"ملفات مشتركة",
    clearChat:"مسح المحادثة", confirmBlock:"هل تريد حظر هذا المستخدم؟", confirmClear:"هل تريد مسح هذه المحادثة؟",
    cancel:"إلغاء", confirm:"تأكيد",
    privacyPanelTitle:"الخصوصية", storagePanelTitle:"التخزين",
    clearedCacheMsg:"عناصر تم مسحها من الذاكرة", couldNotClearCache:"تعذّر مسح الذاكرة",
    fastModernMessaging:"مراسلة سريعة وحديثة.",
    signIn:"تسجيل الدخول", signUp:"إنشاء حساب",
    displayNamePlaceholder:"الاسم المعروض", phoneOptionalPlaceholder:"الهاتف (اختياري)",
    emailPlaceholder:"البريد الإلكتروني", passwordPlaceholder:"كلمة المرور",
    pleaseWait:"يرجى الانتظار...", createAccount:"إنشاء حساب",
    poweredBy:"مدعوم بـ Supabase. رسائلك مُخزَّنة في الوقت الفعلي.",
    authFailed:"فشل المصادقة",
    callBack:"رد الاتصال",
    callingLabel:"جارٍ الاتصال...", connectingLabel:"جارٍ الاتصال...",
    incomingVideoCall:"مكالمة فيديو واردة", incomingVoiceCall:"مكالمة صوتية واردة",
    declineBtn:"رفض", acceptBtn:"قبول",
    speakerBtn:"مكبر", muteBtn:"كتم", unmuteBtn:"إلغاء الكتم",
    endBtn:"إنهاء", cameraBtn:"كاميرا",
    loadingDots:"تحميل...", members:"أعضاء", group:"مجموعة",
    addedToGroup:"تمت الإضافة إلى المجموعة!",
    chatBgTitle:"خلفية المحادثة", chatBgDesc:"اختر خلفية الدردشة",
    adminLabel:"مشرف", editGroup:"تعديل المجموعة", groupPhoto:"صورة المجموعة",
    groupNameEdited:"تم تحديث اسم المجموعة", groupPhotoUpdated:"تم تحديث صورة المجموعة",
    addCaption:"أضف تعليقاً...", storyText:"نص", storyCamera:"صورة", tapCameraToUpload:"اضغط لرفع صورة",
    groupDescription:"وصف المجموعة", addGroupDesc:"إضافة وصف", editDescription:"تعديل الوصف", descriptionHint:"حول المجموعة...",
    inviteViaLink:"دعوة عبر رابط", qrCode:"رمز QR", copyLink:"نسخ الرابط", linkCopied:"تم نسخ الرابط!",
    disappearingMsgs:"الرسائل المؤقتة", disappearOff:"إيقاف", disappear24h:"24 ساعة", disappear7d:"7 أيام", disappear90d:"90 يوماً",
    lockChat:"قفل المحادثة", lockChatDesc:"طلب رمز PIN للفتح", setPIN:"تعيين رمز PIN", enterPIN:"أدخل رمز PIN",
    confirmPIN:"تأكيد رمز PIN", pinSet:"تم تعيين رمز PIN", pinRemoved:"تم إزالة رمز PIN", wrongPIN:"رمز PIN خاطئ",
    muteNotifs:"كتم الإشعارات", mute8h:"8 ساعات", mute1w:"أسبوع", muteAlways:"دائماً",
    unmute:"إلغاء الكتم", mutedLabel:"مكتوم",
    encryptionInfo:"التشفير", encryptTitle:"تشفير طرفي إلى طرفي",
    encryptDesc:"الرسائل والمكالمات في هذه المحادثة محمية بالتشفير الكامل.",
    exportChat:"تصدير المحادثة", chatExported:"تم تصدير المحادثة",
    clearAllMsgs:"مسح جميع الرسائل", chatCleared:"تم مسح المحادثة",
    reportGroup:"الإبلاغ عن المجموعة", reportSent:"تم إرسال البلاغ",
    noResults:"لا توجد نتائج", callMember:"اتصل بعضو",
    searchInChat:"البحث في المحادثة",
    settingsSection:"الإعدادات", accountSection:"الحساب", appearanceSection:"المظهر", helpSection:"المساعدة",
    inviteFriends:"دعوة أصدقاء", starredMessages:"الرسائل المميزة", starredMessagesSub:"المحادثات التي مييّزتها بنجمة",
    broadcastMsg:"رسالة جماعية", broadcastMsgSub:"أرسل لعدة أشخاص دفعة واحدة",
    linkedDevicesLabel:"الأجهزة المرتبطة", linkedDevicesSub:"الجلسات النشطة على حسابك",
    helpFeedback:"المساعدة والملاحظات", helpFeedbackSub:"تواصل مع الدعم أو أرسل ملاحظاتك",
    shareBtn:"مشاركة", inviteShareDesc:"شارك الرابط مع أصدقائك ليتواصلوا معك على Chatrazze",
    noStarredChats:"لا توجد محادثات مميزة", noStarredChatsSub:"اضغط مطوّلاً على محادثة في القائمة لتمييزها بنجمة",
    searchUserPlaceholder:"ابحث عن مستخدم…", nextBtn:"التالي", selectedCount:"مختار",
    typeYourMessage:"اكتب رسالتك…", goBack:"رجوع", personCount:"شخص",
    sentToPrefix:"تم إرسال الرسالة إلى", couldNotSend:"تعذّر الإرسال",
    activeSession:"الجلسة النشطة حالياً على هذا الجهاز", thisDeviceActive:"هذا الجهاز · نشط",
    lastActivity:"آخر نشاط:", devicesNote:"Chatrazze يدعم جلسة واحدة في وقت واحد. يمكنك تسجيل الدخول من أي متصفح وستكون جلستك متزامنة تلقائياً.",
    bioLabel:"السيرة الذاتية", nameLabel:"الاسم", linksLabel:"الروابط", addLinkBtn:"إضافة رابط",
    editBtn:"تعديل", unknownBrowser:"متصفح غير معروف", unknownOS:"نظام غير معروف",
    reply:"رد", copyText:"نسخ النص", deleteMsg:"حذف", replyingTo:"رداً على",
    msgCopied:"تم النسخ!", you:"أنت", forwardMsg:"إعادة إرسال",
  },
  fr: {
    status:"Statut", calls:"Appels", communities:"Communautés", chats:"Discussions", profile:"Profil",
    statusTitle:"Statut", statusSub:"Partagez des moments qui disparaissent en 24h.",
    myStatus:"Mon statut", tapToAdd:"Appuyez pour ajouter un statut",
    recentUpdates:"Mises à jour récentes", noUpdates:"Aucune mise à jour récente",
    noUpdatesDesc:"Les statuts des autres personnes apparaîtront ici.",
    removeStatus:"Supprimer mon statut", newStatus:"Nouveau statut",
    whatsOnMind:"Qu'est-ce qui vous passe par la tête ?", share:"Partager",
    disappears:"Disparaît en 24h", addImage:"Ajouter une image", addText:"Ajouter du texte", preview:"Aperçu",
    language:"Langue",
    welcome:"Bienvenue sur Chatrazze",
    welcomeSub:"Sélectionnez une conversation ou démarrez-en une nouvelle.",
    notifEnabled:"Notifications activées ✓",
    notifBlocked:"Notifications bloquées — modifiez les paramètres",
    notifNotSupported:"Notifications non supportées dans ce navigateur",
    notifActive:"Activé — appuyez pour tester",
    notifDenied:"Bloqué — modifiez les paramètres du navigateur",
    notifPrompt:"Appuyez pour autoriser les notifications",
    browserNotif:"Notifications du navigateur",
    notifSound:"Son de notification",
    notifPreview:"Afficher l'aperçu du message",
    notifPreviewDesc:"Afficher le texte du message dans la notification",
    ringtoneLabel:"Sonnerie de notification", ringtoneTap:"Appuyer pour prévisualiser",
    newMessage:"Nouveau message",
    statusPosted:"Statut publié — visible pendant 24 heures", statusRemoved:"Statut supprimé",
    callEnded:"Appel terminé", missedCall:"Appel manqué", missedCallFrom:"Appel manqué de", callNotAnswered:"Appel sans réponse",
    sentPhoto:"A envoyé une photo", sentVideo:"A envoyé une vidéo", sentVoice:"A envoyé un message vocal", sentFile:"A envoyé un fichier",
    postedNewStatus:"A publié un nouveau statut", unreadMessage:"message non lu", unreadMessages:"messages non lus",
    darkTheme:"Thème sombre", currently:"Actuellement",
    enterSend:"Entrée pour envoyer", enterSendDesc:"Sinon Entrée insère une nouvelle ligne",
    autoplay:"Lecture automatique des vidéos",
    showOnline:"Afficher le statut en ligne", showOnlineDesc:"Permettre aux autres de voir quand vous êtes en ligne",
    showLastSeen:"Afficher la dernière connexion", showLastSeenDesc:"Afficher quand vous avez été actif pour la dernière fois",
    readReceipts:"Accusés de lecture", readReceiptsDesc:"Afficher les doubles coches quand vous lisez les messages",
    privacyNote:"Les préférences de confidentialité sont stockées sur cet appareil.",
    browserStorage:"Stockage du navigateur", clearCache:"Vider le cache local",
    clearCacheDesc:"Supprime les thèmes et les paramètres locaux",
    storageNote:"Les messages restent sécurisés dans le cloud.",
    used:"utilisé sur", available:"disponible",
    image:"Image", video:"Vidéo", file:"Fichier / PDF",
    typeMessage:"Écrivez un message",
    today:"Aujourd'hui", yesterday:"Hier",
    online:"en ligne", typing:"écrit...", lastSeen:"dernière connexion",
    justNow:"à l'instant", minAgo:"min", hAgo:"h",
    noMessages:"Aucun message — dites bonjour !",
    sendImage:"Envoyer une image", sendVideo:"Envoyer une vidéo", sendFile:"Envoyer un fichier",
    uploading:"Envoi en cours", uploadFailed:"Échec de l'envoi",
    voiceMessage:"Message vocal", stopRecording:"Arrêter l'enregistrement",
    micDenied:"Accès au microphone refusé.",
    switchToLight:"Passer au clair", switchToDark:"Passer au sombre",
    lightTheme:"Thème clair", lightThemeOn:"Thème clair activé", darkThemeOn:"Thème sombre activé",
    profileTitle:"Profil",
    accountSetting:"Compte", privacySetting:"Confidentialité",
    privacySettingSub:"Statut en ligne, dernière connexion, accusés de lecture",
    chatsSetting:"Discussions", chatsSettingSub:"Thème, touche d'envoi, lecture auto",
    notificationsSetting:"Notifications", notificationsSettingSub:"Alertes navigateur, son, aperçu",
    storageDataSetting:"Stockage et données", storageDataSub:"Stockage navigateur, vider le cache",
    tapToCopyId:"Appuyez pour copier votre identifiant", userIdCopied:"Identifiant copié",
    logOut:"Se déconnecter",
    profilePhotoUpdated:"Photo de profil mise à jour", couldNotUploadPhoto:"Impossible de télécharger la photo",
    profileSaved:"Profil enregistré", couldNotSaveProfile:"Impossible d'enregistrer le profil",
    pleasePickImage:"Veuillez choisir un fichier image", imageTooLarge:"L'image doit faire moins de 5 Mo",
    save:"Enregistrer", saving:"Enregistrement...", defaultBio:"Salut ! J'utilise Chatrazze.",
    recentCallHistory:"Historique des appels récents.",
    noCallsYet:"Aucun appel pour l'instant",
    noCallsDesc:"Les appels vocaux et vidéo apparaîtront ici après un appel.",
    callTypesLabel:"Types d'appels", incoming:"Entrant", outgoing:"Sortant", missed:"Manqué",
    callHistoryCleared:"Historique des appels effacé", dAgo:"j",
    newChat:"Nouvelle discussion", newGroup:"Nouveau groupe",
    searchChatsMessages:"Rechercher des discussions et messages",
    filterAll:"Tout", filterUnread:"Non lus", filterFavorites:"Favoris", filterGroups:"Groupes",
    noChatsFilter:"Aucune discussion ne correspond au filtre.", noChatsYet:"Aucune discussion. Appuyez sur + pour commencer.",
    sayHi:"Dites bonjour", removeFavorite:"Retirer des favoris", markFavorite:"Ajouter aux favoris",
    searchByNameOrId:"Rechercher par nom ou identifiant",
    searching:"Recherche...", noUsersFound:"Aucun utilisateur trouvé.",
    groupNameLabel:"Nom du groupe", enterGroupName:"Entrez le nom du groupe...",
    addMembersLabel:"Ajouter des membres", searchUsersPlaceholder:"Rechercher des utilisateurs...",
    creating:"Création…", createGroupBtn:"Créer le groupe",
    groupInfo:"Infos du groupe", membersCount:"membres",
    messagesLabel:"Messages", photosLabel:"Photos", videosLabel:"Vidéos",
    voiceLabel:"Vocal", filesLabel:"Fichiers",
    moreActions:"Plus d'actions", viewAllMembers:"Voir tous les membres", showLessMembers:"Voir moins",
    addMember:"Ajouter un membre", loadingMembers:"Chargement des membres...",
    youSuffix:"(Vous)", onlineCapital:"En ligne", offlineCapital:"Hors ligne",
    noMediaShared:"Aucun média partagé.", noFilesShared:"Aucun fichier partagé.",
    leaveGroup:"Quitter le groupe", leavingGroup:"Départ...", leftGroup:"Vous avez quitté le groupe.",
    searchByName:"Rechercher par nom...",
    typeNameToFind:"Tapez un nom pour trouver quelqu'un.",
    notInGroup:"Aucun utilisateur trouvé — ou déjà membre du groupe.",
    adding:"Ajout…", add:"Ajouter",
    contactInfo:"Infos du contact", emailLabel:"E-mail", phoneLabel:"Téléphone",
    voiceMessagesLabel:"Messages vocaux", voiceMessagesCount:"messages vocaux",
    voiceCallBtn:"Vocal", videoCallBtn:"Vidéo",
    mediaTab:"Médias", filesTab:"Fichiers",
    unblockUser:"Débloquer", blockUser:"Bloquer",
    privacyPanelTitle:"Confidentialité", storagePanelTitle:"Stockage",
    clearedCacheMsg:"éléments supprimés du cache", couldNotClearCache:"Impossible de vider le cache",
    fastModernMessaging:"Messagerie rapide et moderne.",
    signIn:"Se connecter", signUp:"S'inscrire",
    displayNamePlaceholder:"Nom d'affichage", phoneOptionalPlaceholder:"Téléphone (optionnel)",
    emailPlaceholder:"E-mail", passwordPlaceholder:"Mot de passe",
    pleaseWait:"Veuillez patienter...", createAccount:"Créer un compte",
    poweredBy:"Propulsé par Supabase. Vos messages sont stockés en temps réel.",
    authFailed:"Échec de l'authentification",
    callBack:"Rappeler",
    callingLabel:"Appel en cours...", connectingLabel:"Connexion...",
    incomingVideoCall:"Appel vidéo entrant", incomingVoiceCall:"Appel vocal entrant",
    declineBtn:"Refuser", acceptBtn:"Accepter",
    speakerBtn:"Haut-parleur", muteBtn:"Couper le son", unmuteBtn:"Rétablir le son",
    endBtn:"Terminer", cameraBtn:"Caméra",
    loadingDots:"Chargement...", members:"membres", group:"Groupe",
    addedToGroup:"ajouté au groupe !",
    chatBgTitle:"Fond de discussion", chatBgDesc:"Choisissez votre fond",
    adminLabel:"Admin", editGroup:"Modifier le groupe", groupPhoto:"Photo du groupe",
    groupNameEdited:"Nom du groupe mis à jour", groupPhotoUpdated:"Photo du groupe mise à jour",
    addCaption:"Ajouter une légende...", storyText:"Texte", storyCamera:"Photo", tapCameraToUpload:"Appuyez pour télécharger",
    groupDescription:"Description du groupe", addGroupDesc:"Ajouter une description", editDescription:"Modifier la description", descriptionHint:"À propos du groupe...",
    inviteViaLink:"Inviter via un lien", qrCode:"Code QR", copyLink:"Copier le lien", linkCopied:"Lien copié !",
    disappearingMsgs:"Messages éphémères", disappearOff:"Désactivé", disappear24h:"24 heures", disappear7d:"7 jours", disappear90d:"90 jours",
    lockChat:"Verrouiller la discussion", lockChatDesc:"Exiger un code PIN pour ouvrir", setPIN:"Définir le code PIN", enterPIN:"Entrer le code PIN",
    confirmPIN:"Confirmer le code PIN", pinSet:"Code PIN défini", pinRemoved:"Code PIN supprimé", wrongPIN:"Code PIN incorrect",
    muteNotifs:"Désactiver les notifications", mute8h:"8 heures", mute1w:"1 semaine", muteAlways:"Toujours",
    unmute:"Réactiver", mutedLabel:"Silencieux",
    encryptionInfo:"Chiffrement", encryptTitle:"Chiffrement de bout en bout",
    encryptDesc:"Les messages et appels dans cette discussion sont sécurisés par le chiffrement de bout en bout.",
    exportChat:"Exporter la discussion", chatExported:"Discussion exportée",
    clearAllMsgs:"Effacer tous les messages", chatCleared:"Discussion effacée",
    reportGroup:"Signaler le groupe", reportSent:"Signalement envoyé",
    noResults:"Aucun résultat", callMember:"Appeler un membre",
    searchInChat:"Rechercher dans la discussion",
    settingsSection:"Paramètres", accountSection:"Compte", appearanceSection:"Apparence", helpSection:"Aide",
    inviteFriends:"Inviter des amis", starredMessages:"Messages favoris", starredMessagesSub:"Discussions marquées comme favorites",
    broadcastMsg:"Message groupé", broadcastMsgSub:"Envoyer à plusieurs personnes à la fois",
    linkedDevicesLabel:"Appareils liés", linkedDevicesSub:"Sessions actives sur votre compte",
    helpFeedback:"Aide et commentaires", helpFeedbackSub:"Contacter le support ou envoyer des commentaires",
    shareBtn:"Partager", inviteShareDesc:"Partagez le lien avec vos amis pour se connecter sur Chatrazze",
    noStarredChats:"Aucune discussion favorite", noStarredChatsSub:"Appuyez longuement sur une discussion pour la marquer",
    searchUserPlaceholder:"Rechercher un utilisateur…", nextBtn:"Suivant", selectedCount:"sélectionné(s)",
    typeYourMessage:"Écrivez votre message…", goBack:"Retour", personCount:"personne(s)",
    sentToPrefix:"Message envoyé à", couldNotSend:"Envoi impossible",
    activeSession:"Session active sur cet appareil", thisDeviceActive:"Cet appareil · Actif",
    lastActivity:"Dernière activité :", devicesNote:"Chatrazze prend en charge une seule session à la fois. Connectez-vous depuis n'importe quel navigateur et votre session se synchronise automatiquement.",
    bioLabel:"Bio", nameLabel:"Nom", linksLabel:"Liens", addLinkBtn:"Ajouter un lien",
    editBtn:"Modifier", cancel:"Annuler", unknownBrowser:"Navigateur inconnu", unknownOS:"Système inconnu",
    reply:"Répondre", copyText:"Copier le texte", deleteMsg:"Supprimer", replyingTo:"En réponse à",
    msgCopied:"Copié!", you:"Vous", forwardMsg:"Transférer",
  },
  es: {
    status:"Estado", calls:"Llamadas", communities:"Comunidades", chats:"Chats", profile:"Perfil",
    statusTitle:"Estado", statusSub:"Comparte momentos que desaparecen en 24h.",
    myStatus:"Mi estado", tapToAdd:"Toca para añadir estado",
    recentUpdates:"Actualizaciones recientes", noUpdates:"Sin actualizaciones recientes",
    noUpdatesDesc:"Los estados de otras personas aparecerán aquí.",
    removeStatus:"Eliminar mi estado", newStatus:"Nuevo estado",
    whatsOnMind:"¿Qué tienes en mente?", share:"Compartir",
    disappears:"Desaparece en 24h", addImage:"Agregar imagen", addText:"Agregar texto", preview:"Vista previa",
    language:"Idioma",
    welcome:"Bienvenido a Chatrazze",
    welcomeSub:"Selecciona una conversación o inicia una nueva.",
    notifEnabled:"Notificaciones activadas ✓",
    notifBlocked:"Notificaciones bloqueadas — cambia los ajustes",
    notifNotSupported:"Notificaciones no soportadas en este navegador",
    notifActive:"Activado — toca para probar",
    notifDenied:"Bloqueado — cambia los ajustes del navegador",
    notifPrompt:"Toca para permitir notificaciones",
    browserNotif:"Notificaciones del navegador",
    notifSound:"Sonido de notificación",
    notifPreview:"Mostrar vista previa del mensaje",
    notifPreviewDesc:"Mostrar el texto del mensaje en la notificación",
    ringtoneLabel:"Tono de notificación", ringtoneTap:"Toca para previsualizar",
    newMessage:"Nuevo mensaje",
    statusPosted:"Estado publicado — visible por 24 horas", statusRemoved:"Estado eliminado",
    callEnded:"Llamada finalizada", missedCall:"Llamada perdida", missedCallFrom:"Llamada perdida de", callNotAnswered:"Llamada sin respuesta",
    sentPhoto:"Envió una foto", sentVideo:"Envió un video", sentVoice:"Envió un mensaje de voz", sentFile:"Envió un archivo",
    postedNewStatus:"Publicó un nuevo estado", unreadMessage:"mensaje sin leer", unreadMessages:"mensajes sin leer",
    darkTheme:"Tema oscuro", currently:"Actualmente",
    enterSend:"Enter para enviar", enterSendDesc:"De lo contrario Enter inserta una nueva línea",
    autoplay:"Reproducción automática de videos",
    showOnline:"Mostrar estado en línea", showOnlineDesc:"Permitir que otros vean cuando estás en línea",
    showLastSeen:"Mostrar última vez visto", showLastSeenDesc:"Mostrar cuándo estuviste activo por última vez",
    readReceipts:"Confirmaciones de lectura", readReceiptsDesc:"Mostrar doble tilde cuando lees mensajes",
    privacyNote:"Las preferencias de privacidad se almacenan en este dispositivo.",
    browserStorage:"Almacenamiento del navegador", clearCache:"Limpiar caché local",
    clearCacheDesc:"Elimina temas y configuraciones locales",
    storageNote:"Los mensajes permanecen seguros en la nube.",
    used:"usado de", available:"disponible",
    image:"Imagen", video:"Video", file:"Archivo / PDF",
    typeMessage:"Escribe un mensaje",
    today:"Hoy", yesterday:"Ayer",
    online:"en línea", typing:"escribiendo...", lastSeen:"última vez",
    justNow:"ahora mismo", minAgo:"min", hAgo:"h",
    noMessages:"Sin mensajes — ¡di hola!",
    sendImage:"Enviar imagen", sendVideo:"Enviar video", sendFile:"Enviar archivo",
    uploading:"Subiendo", uploadFailed:"Error al subir",
    voiceMessage:"Mensaje de voz", stopRecording:"Detener grabación",
    micDenied:"Acceso al micrófono denegado.",
    switchToLight:"Cambiar a claro", switchToDark:"Cambiar a oscuro",
    lightTheme:"Tema claro", lightThemeOn:"Tema claro activado", darkThemeOn:"Tema oscuro activado",
    profileTitle:"Perfil",
    accountSetting:"Cuenta", privacySetting:"Privacidad",
    privacySettingSub:"Estado en línea, última vez visto, confirmaciones de lectura",
    chatsSetting:"Chats", chatsSettingSub:"Tema, tecla de envío, reproducción automática",
    notificationsSetting:"Notificaciones", notificationsSettingSub:"Alertas del navegador, sonido, vista previa",
    storageDataSetting:"Almacenamiento y datos", storageDataSub:"Almacenamiento, limpiar caché",
    tapToCopyId:"Toca para copiar tu ID único", userIdCopied:"ID de usuario copiado",
    logOut:"Cerrar sesión",
    profilePhotoUpdated:"Foto de perfil actualizada", couldNotUploadPhoto:"No se pudo subir la foto",
    profileSaved:"Perfil guardado", couldNotSaveProfile:"No se pudo guardar el perfil",
    pleasePickImage:"Por favor elige un archivo de imagen", imageTooLarge:"La imagen debe pesar menos de 5 MB",
    save:"Guardar", saving:"Guardando...", defaultBio:"¡Hola! Estoy usando Chatrazze.",
    recentCallHistory:"Historial de llamadas recientes.",
    noCallsYet:"Sin llamadas todavía",
    noCallsDesc:"Las llamadas de voz y video aparecerán aquí después de una llamada.",
    callTypesLabel:"Tipos de llamadas", incoming:"Entrante", outgoing:"Saliente", missed:"Perdida",
    callHistoryCleared:"Historial de llamadas borrado", dAgo:"d",
    newChat:"Nuevo chat", newGroup:"Nuevo grupo",
    searchChatsMessages:"Buscar chats y mensajes",
    filterAll:"Todos", filterUnread:"No leídos", filterFavorites:"Favoritos", filterGroups:"Grupos",
    noChatsFilter:"Ningún chat coincide con el filtro.", noChatsYet:"Sin chats. Pulsa + para empezar.",
    sayHi:"Di hola", removeFavorite:"Quitar de favoritos", markFavorite:"Agregar a favoritos",
    searchByNameOrId:"Buscar por nombre o ID de usuario",
    searching:"Buscando...", noUsersFound:"No se encontraron usuarios.",
    groupNameLabel:"Nombre del grupo", enterGroupName:"Introduce el nombre del grupo...",
    addMembersLabel:"Agregar miembros", searchUsersPlaceholder:"Buscar usuarios...",
    creating:"Creando…", createGroupBtn:"Crear grupo",
    groupInfo:"Info del grupo", membersCount:"miembros",
    messagesLabel:"Mensajes", photosLabel:"Fotos", videosLabel:"Videos",
    voiceLabel:"Voz", filesLabel:"Archivos",
    addMember:"Agregar miembro", loadingMembers:"Cargando miembros...",
    youSuffix:"(Tú)", onlineCapital:"En línea", offlineCapital:"Sin conexión",
    noMediaShared:"No hay medios compartidos.", noFilesShared:"No hay archivos compartidos.",
    leaveGroup:"Salir del grupo", leavingGroup:"Saliendo...", leftGroup:"Saliste del grupo.",
    searchByName:"Buscar por nombre...",
    typeNameToFind:"Escribe un nombre para encontrar a alguien.",
    notInGroup:"No se encontraron usuarios — o ya son miembros.",
    adding:"Agregando…", add:"Agregar",
    contactInfo:"Info del contacto", emailLabel:"Correo", phoneLabel:"Teléfono",
    voiceMessagesLabel:"Mensajes de voz", voiceMessagesCount:"mensajes de voz",
    voiceCallBtn:"Voz", videoCallBtn:"Video",
    mediaTab:"Medios", filesTab:"Archivos",
    unblockUser:"Desbloquear", blockUser:"Bloquear",
    privacyPanelTitle:"Privacidad", storagePanelTitle:"Almacenamiento",
    clearedCacheMsg:"elementos eliminados del caché", couldNotClearCache:"No se pudo limpiar el caché",
    fastModernMessaging:"Mensajería rápida y moderna.",
    signIn:"Iniciar sesión", signUp:"Registrarse",
    displayNamePlaceholder:"Nombre visible", phoneOptionalPlaceholder:"Teléfono (opcional)",
    emailPlaceholder:"Correo electrónico", passwordPlaceholder:"Contraseña",
    pleaseWait:"Por favor espera...", createAccount:"Crear cuenta",
    poweredBy:"Desarrollado con Supabase. Tus mensajes se almacenan en tiempo real.",
    authFailed:"Error de autenticación",
    callBack:"Devolver llamada",
    callingLabel:"Llamando...", connectingLabel:"Conectando...",
    incomingVideoCall:"Videollamada entrante", incomingVoiceCall:"Llamada de voz entrante",
    declineBtn:"Rechazar", acceptBtn:"Aceptar",
    speakerBtn:"Altavoz", muteBtn:"Silenciar", unmuteBtn:"Activar sonido",
    endBtn:"Terminar", cameraBtn:"Cámara",
    loadingDots:"Cargando...", members:"miembros", group:"Grupo",
    addedToGroup:"¡agregado al grupo!",
    chatBgTitle:"Fondo del chat", chatBgDesc:"Elige tu fondo",
    adminLabel:"Admin", editGroup:"Editar grupo", groupPhoto:"Foto del grupo",
    groupNameEdited:"Nombre del grupo actualizado", groupPhotoUpdated:"Foto del grupo actualizada",
    addCaption:"Añadir descripción...", storyText:"Texto", storyCamera:"Foto", tapCameraToUpload:"Toca para subir foto",
    groupDescription:"Descripción del grupo", addGroupDesc:"Agregar descripción", editDescription:"Editar descripción", descriptionHint:"Acerca del grupo...",
    inviteViaLink:"Invitar mediante enlace", qrCode:"Código QR", copyLink:"Copiar enlace", linkCopied:"¡Enlace copiado!",
    disappearingMsgs:"Mensajes temporales", disappearOff:"Desactivado", disappear24h:"24 horas", disappear7d:"7 días", disappear90d:"90 días",
    lockChat:"Bloquear chat", lockChatDesc:"Requerir PIN para abrir", setPIN:"Establecer PIN", enterPIN:"Ingresar PIN",
    confirmPIN:"Confirmar PIN", pinSet:"PIN establecido", pinRemoved:"PIN eliminado", wrongPIN:"PIN incorrecto",
    muteNotifs:"Silenciar notificaciones", mute8h:"8 horas", mute1w:"1 semana", muteAlways:"Siempre",
    unmute:"Activar sonido", mutedLabel:"Silenciado",
    encryptionInfo:"Cifrado", encryptTitle:"Cifrado de extremo a extremo",
    encryptDesc:"Los mensajes y llamadas en este chat están protegidos con cifrado de extremo a extremo.",
    exportChat:"Exportar chat", chatExported:"Chat exportado",
    clearAllMsgs:"Borrar todos los mensajes", chatCleared:"Chat borrado",
    reportGroup:"Reportar grupo", reportSent:"Reporte enviado",
    noResults:"Sin resultados", callMember:"Llamar a miembro",
    searchInChat:"Buscar en el chat",
    settingsSection:"Configuración", accountSection:"Cuenta", appearanceSection:"Apariencia", helpSection:"Ayuda",
    inviteFriends:"Invitar amigos", starredMessages:"Mensajes destacados", starredMessagesSub:"Chats que has destacado",
    broadcastMsg:"Mensaje masivo", broadcastMsgSub:"Envía a varias personas a la vez",
    linkedDevicesLabel:"Dispositivos vinculados", linkedDevicesSub:"Sesiones activas en tu cuenta",
    helpFeedback:"Ayuda y comentarios", helpFeedbackSub:"Contacta soporte o envía comentarios",
    shareBtn:"Compartir", inviteShareDesc:"Comparte el enlace con tus amigos para conectar en Chatrazze",
    noStarredChats:"No hay chats destacados", noStarredChatsSub:"Mantén presionado un chat para destacarlo",
    searchUserPlaceholder:"Buscar usuario…", nextBtn:"Siguiente", selectedCount:"seleccionado(s)",
    typeYourMessage:"Escribe tu mensaje…", goBack:"Volver", personCount:"persona(s)",
    sentToPrefix:"Mensaje enviado a", couldNotSend:"No se pudo enviar",
    activeSession:"Sesión activa en este dispositivo", thisDeviceActive:"Este dispositivo · Activo",
    lastActivity:"Última actividad:", devicesNote:"Chatrazze admite una sola sesión a la vez. Inicia sesión desde cualquier navegador y tu sesión se sincroniza automáticamente.",
    bioLabel:"Biografía", nameLabel:"Nombre", linksLabel:"Enlaces", addLinkBtn:"Añadir enlace",
    editBtn:"Editar", cancel:"Cancelar", unknownBrowser:"Navegador desconocido", unknownOS:"Sistema desconocido",
    reply:"Responder", copyText:"Copiar texto", deleteMsg:"Eliminar", replyingTo:"Respondiendo a",
    msgCopied:"¡Copiado!", you:"Tú", forwardMsg:"Reenviar",
  },
  de: {
    status:"Status", calls:"Anrufe", communities:"Gruppen", chats:"Chats", profile:"Profil",
    statusTitle:"Status", statusSub:"Teile Momente, die nach 24h verschwinden.",
    myStatus:"Mein Status", tapToAdd:"Tippen um Status hinzuzufügen",
    recentUpdates:"Aktuelle Updates", noUpdates:"Keine aktuellen Updates",
    noUpdatesDesc:"Status-Updates von anderen Personen erscheinen hier.",
    removeStatus:"Status entfernen", newStatus:"Neuer Status",
    whatsOnMind:"Was denkst du gerade?", share:"Teilen",
    disappears:"Verschwindet in 24h", addImage:"Bild hinzufügen", addText:"Text hinzufügen", preview:"Vorschau",
    language:"Sprache",
    welcome:"Willkommen bei Chatrazze",
    welcomeSub:"Wähle ein Gespräch aus oder starte ein neues.",
    notifEnabled:"Benachrichtigungen aktiviert ✓",
    notifBlocked:"Benachrichtigungen blockiert — Einstellungen ändern",
    notifNotSupported:"Benachrichtigungen werden in diesem Browser nicht unterstützt",
    notifActive:"Aktiviert — zum Testen tippen",
    notifDenied:"Blockiert — Browser-Einstellungen ändern",
    notifPrompt:"Tippen um Benachrichtigungen zu erlauben",
    browserNotif:"Browser-Benachrichtigungen",
    notifSound:"Benachrichtigungston",
    notifPreview:"Nachrichtenvorschau anzeigen",
    notifPreviewDesc:"Nachrichtentext in der Benachrichtigung anzeigen",
    ringtoneLabel:"Benachrichtigungsklingelton", ringtoneTap:"Zum Vorhören tippen",
    newMessage:"Neue Nachricht",
    statusPosted:"Status veröffentlicht — 24 Stunden sichtbar", statusRemoved:"Status entfernt",
    callEnded:"Anruf beendet", missedCall:"Verpasster Anruf", missedCallFrom:"Verpasster Anruf von", callNotAnswered:"Anruf nicht beantwortet",
    sentPhoto:"Hat ein Foto gesendet", sentVideo:"Hat ein Video gesendet", sentVoice:"Hat eine Sprachnachricht gesendet", sentFile:"Hat eine Datei gesendet",
    postedNewStatus:"Hat einen neuen Status veröffentlicht", unreadMessage:"ungelesene Nachricht", unreadMessages:"ungelesene Nachrichten",
    darkTheme:"Dunkles Thema", currently:"Aktuell",
    enterSend:"Enter zum Senden", enterSendDesc:"Sonst fügt Enter eine neue Zeile ein",
    autoplay:"Videos automatisch abspielen",
    showOnline:"Online-Status anzeigen", showOnlineDesc:"Anderen zeigen, wann du online bist",
    showLastSeen:"Zuletzt gesehen anzeigen", showLastSeenDesc:"Zeige wann du zuletzt aktiv warst",
    readReceipts:"Lesebestätigungen", readReceiptsDesc:"Doppelte Häkchen beim Lesen anzeigen",
    privacyNote:"Datenschutzeinstellungen werden auf diesem Gerät gespeichert.",
    browserStorage:"Browser-Speicher", clearCache:"Lokalen Cache leeren",
    clearCacheDesc:"Entfernt Designs und lokale Einstellungen",
    storageNote:"Nachrichten bleiben sicher in der Cloud.",
    used:"verwendet von", available:"verfügbar",
    image:"Bild", video:"Video", file:"Datei / PDF",
    typeMessage:"Nachricht eingeben",
    today:"Heute", yesterday:"Gestern",
    online:"online", typing:"tippt...", lastSeen:"zuletzt gesehen",
    justNow:"gerade eben", minAgo:"Min", hAgo:"Std",
    noMessages:"Noch keine Nachrichten — sag Hallo!",
    sendImage:"Bild senden", sendVideo:"Video senden", sendFile:"Datei senden",
    uploading:"Hochladen", uploadFailed:"Upload fehlgeschlagen",
    voiceMessage:"Sprachnachricht", stopRecording:"Aufnahme stoppen",
    micDenied:"Mikrofonzugriff verweigert.",
    switchToLight:"Zum hellen Modus", switchToDark:"Zum dunklen Modus",
    lightTheme:"Helles Thema", lightThemeOn:"Helles Thema aktiviert", darkThemeOn:"Dunkles Thema aktiviert",
    profileTitle:"Profil",
    accountSetting:"Konto", privacySetting:"Datenschutz",
    privacySettingSub:"Online-Status, zuletzt gesehen, Lesebestätigungen",
    chatsSetting:"Chats", chatsSettingSub:"Thema, Sendtaste, Autoplay",
    notificationsSetting:"Benachrichtigungen", notificationsSettingSub:"Browser-Benachrichtigungen, Ton, Vorschau",
    storageDataSetting:"Speicher & Daten", storageDataSub:"Browser-Speicher, Cache leeren",
    tapToCopyId:"Tippen um deine ID zu kopieren", userIdCopied:"Benutzer-ID kopiert",
    logOut:"Abmelden",
    profilePhotoUpdated:"Profilbild aktualisiert", couldNotUploadPhoto:"Foto konnte nicht hochgeladen werden",
    profileSaved:"Profil gespeichert", couldNotSaveProfile:"Profil konnte nicht gespeichert werden",
    pleasePickImage:"Bitte wähle eine Bilddatei", imageTooLarge:"Das Bild muss kleiner als 5 MB sein",
    save:"Speichern", saving:"Speichern...", defaultBio:"Hallo! Ich benutze Chatrazze.",
    recentCallHistory:"Neueste Anrufe.",
    noCallsYet:"Noch keine Anrufe",
    noCallsDesc:"Sprach- und Videoanrufe erscheinen hier nach einem Anruf.",
    callTypesLabel:"Anruftypen", incoming:"Eingehend", outgoing:"Ausgehend", missed:"Verpasst",
    callHistoryCleared:"Anrufverlauf gelöscht", dAgo:"T",
    newChat:"Neuer Chat", newGroup:"Neue Gruppe",
    searchChatsMessages:"Chats und Nachrichten durchsuchen",
    filterAll:"Alle", filterUnread:"Ungelesen", filterFavorites:"Favoriten", filterGroups:"Gruppen",
    noChatsFilter:"Keine Chats entsprechen dem Filter.", noChatsYet:"Keine Chats. Tippe + zum Starten.",
    sayHi:"Sag Hallo", removeFavorite:"Aus Favoriten entfernen", markFavorite:"Als Favorit markieren",
    searchByNameOrId:"Nach Name oder Benutzer-ID suchen",
    searching:"Suche...", noUsersFound:"Keine Benutzer gefunden.",
    groupNameLabel:"Gruppenname", enterGroupName:"Gruppenname eingeben...",
    addMembersLabel:"Mitglieder hinzufügen", searchUsersPlaceholder:"Benutzer suchen...",
    creating:"Erstellen…", createGroupBtn:"Gruppe erstellen",
    groupInfo:"Gruppeninfo", membersCount:"Mitglieder",
    messagesLabel:"Nachrichten", photosLabel:"Fotos", videosLabel:"Videos",
    voiceLabel:"Sprache", filesLabel:"Dateien",
    moreActions:"Mehr Aktionen", viewAllMembers:"Alle Mitglieder anzeigen", showLessMembers:"Weniger anzeigen",
    addMember:"Mitglied hinzufügen", loadingMembers:"Mitglieder laden...",
    youSuffix:"(Du)", onlineCapital:"Online", offlineCapital:"Offline",
    noMediaShared:"Keine Medien geteilt.", noFilesShared:"Keine Dateien geteilt.",
    leaveGroup:"Gruppe verlassen", leavingGroup:"Verlassen...", leftGroup:"Du hast die Gruppe verlassen.",
    searchByName:"Nach Namen suchen...",
    typeNameToFind:"Namen eingeben um jemanden zu finden.",
    notInGroup:"Keine Benutzer gefunden — oder bereits Mitglied.",
    adding:"Hinzufügen…", add:"Hinzufügen",
    contactInfo:"Kontaktinfo", emailLabel:"E-Mail", phoneLabel:"Telefon",
    voiceMessagesLabel:"Sprachnachrichten", voiceMessagesCount:"Sprachnachrichten",
    voiceCallBtn:"Sprache", videoCallBtn:"Video",
    mediaTab:"Medien", filesTab:"Dateien",
    unblockUser:"Entsperren", blockUser:"Sperren",
    privacyPanelTitle:"Datenschutz", storagePanelTitle:"Speicher",
    clearedCacheMsg:"gecachte Elemente gelöscht", couldNotClearCache:"Cache konnte nicht geleert werden",
    fastModernMessaging:"Schnelles, modernes Messaging.",
    signIn:"Anmelden", signUp:"Registrieren",
    displayNamePlaceholder:"Anzeigename", phoneOptionalPlaceholder:"Telefon (optional)",
    emailPlaceholder:"E-Mail", passwordPlaceholder:"Passwort",
    pleaseWait:"Bitte warten...", createAccount:"Konto erstellen",
    poweredBy:"Powered by Supabase. Deine Nachrichten werden in Echtzeit gespeichert.",
    authFailed:"Authentifizierung fehlgeschlagen",
    callBack:"Zurückrufen",
    callingLabel:"Anrufen...", connectingLabel:"Verbinden...",
    incomingVideoCall:"Eingehender Videoanruf", incomingVoiceCall:"Eingehender Sprachanruf",
    declineBtn:"Ablehnen", acceptBtn:"Annehmen",
    speakerBtn:"Lautsprecher", muteBtn:"Stummschalten", unmuteBtn:"Stummschaltung aufheben",
    endBtn:"Beenden", cameraBtn:"Kamera",
    loadingDots:"Laden...", members:"Mitglieder", group:"Gruppe",
    addedToGroup:"zur Gruppe hinzugefügt!",
    chatBgTitle:"Chat-Hintergrund", chatBgDesc:"Wähle deinen Hintergrund",
    adminLabel:"Admin", editGroup:"Gruppe bearbeiten", groupPhoto:"Gruppenfoto",
    groupNameEdited:"Gruppenname aktualisiert", groupPhotoUpdated:"Gruppenfoto aktualisiert",
    addCaption:"Beschriftung hinzufügen...", storyText:"Text", storyCamera:"Foto", tapCameraToUpload:"Tippen zum Hochladen",
    groupDescription:"Gruppenbeschreibung", addGroupDesc:"Beschreibung hinzufügen", editDescription:"Beschreibung bearbeiten", descriptionHint:"Über die Gruppe...",
    inviteViaLink:"Per Link einladen", qrCode:"QR-Code", copyLink:"Link kopieren", linkCopied:"Link kopiert!",
    disappearingMsgs:"Selbstlöschende Nachrichten", disappearOff:"Aus", disappear24h:"24 Stunden", disappear7d:"7 Tage", disappear90d:"90 Tage",
    lockChat:"Chat sperren", lockChatDesc:"PIN zum Öffnen erforderlich", setPIN:"PIN festlegen", enterPIN:"PIN eingeben",
    confirmPIN:"PIN bestätigen", pinSet:"PIN festgelegt", pinRemoved:"PIN entfernt", wrongPIN:"Falscher PIN",
    muteNotifs:"Benachrichtigungen stummschalten", mute8h:"8 Stunden", mute1w:"1 Woche", muteAlways:"Immer",
    unmute:"Stummschaltung aufheben", mutedLabel:"Stummgeschaltet",
    encryptionInfo:"Verschlüsselung", encryptTitle:"Ende-zu-Ende verschlüsselt",
    encryptDesc:"Nachrichten und Anrufe in diesem Chat sind durch Ende-zu-Ende-Verschlüsselung gesichert.",
    exportChat:"Chat exportieren", chatExported:"Chat exportiert",
    clearAllMsgs:"Alle Nachrichten löschen", chatCleared:"Chat geleert",
    reportGroup:"Gruppe melden", reportSent:"Meldung gesendet",
    noResults:"Keine Ergebnisse", callMember:"Mitglied anrufen",
    searchInChat:"Im Chat suchen",
    settingsSection:"Einstellungen", accountSection:"Konto", appearanceSection:"Erscheinungsbild", helpSection:"Hilfe",
    inviteFriends:"Freunde einladen", starredMessages:"Markierte Nachrichten", starredMessagesSub:"Markierte Chats",
    broadcastMsg:"Broadcast-Nachricht", broadcastMsgSub:"An mehrere Personen gleichzeitig senden",
    linkedDevicesLabel:"Verknüpfte Geräte", linkedDevicesSub:"Aktive Sitzungen auf deinem Konto",
    helpFeedback:"Hilfe & Feedback", helpFeedbackSub:"Support kontaktieren oder Feedback senden",
    shareBtn:"Teilen", inviteShareDesc:"Teile den Link mit deinen Freunden, um auf Chatrazze zu verbinden",
    noStarredChats:"Keine markierten Chats", noStarredChatsSub:"Halte einen Chat gedrückt, um ihn zu markieren",
    searchUserPlaceholder:"Benutzer suchen…", nextBtn:"Weiter", selectedCount:"ausgewählt",
    typeYourMessage:"Schreib eine Nachricht…", goBack:"Zurück", personCount:"Person(en)",
    sentToPrefix:"Nachricht gesendet an", couldNotSend:"Senden fehlgeschlagen",
    activeSession:"Aktuelle Sitzung auf diesem Gerät", thisDeviceActive:"Dieses Gerät · Aktiv",
    lastActivity:"Letzte Aktivität:", devicesNote:"Chatrazze unterstützt jeweils eine Sitzung. Melde dich von jedem Browser an und deine Sitzung wird automatisch synchronisiert.",
    bioLabel:"Bio", nameLabel:"Name", linksLabel:"Links", addLinkBtn:"Link hinzufügen",
    editBtn:"Bearbeiten", cancel:"Abbrechen", unknownBrowser:"Unbekannter Browser", unknownOS:"Unbekanntes System",
    reply:"Antworten", copyText:"Text kopieren", deleteMsg:"Löschen", replyingTo:"Antwort an",
    msgCopied:"Kopiert!", you:"Du", forwardMsg:"Weiterleiten",
  },
  pt: {
    status:"Status", calls:"Chamadas", communities:"Comunidades", chats:"Conversas", profile:"Perfil",
    statusTitle:"Status", statusSub:"Compartilhe momentos que desaparecem em 24h.",
    myStatus:"Meu status", tapToAdd:"Toque para adicionar status",
    recentUpdates:"Atualizações recentes", noUpdates:"Sem atualizações recentes",
    noUpdatesDesc:"Os status de outras pessoas aparecerão aqui.",
    removeStatus:"Remover meu status", newStatus:"Novo status",
    whatsOnMind:"O que você está pensando?", share:"Compartilhar",
    disappears:"Desaparece em 24h", addImage:"Adicionar imagem", addText:"Adicionar texto", preview:"Visualizar",
    language:"Idioma",
    welcome:"Bem-vindo ao Chatrazze",
    welcomeSub:"Selecione uma conversa ou inicie uma nova.",
    notifEnabled:"Notificações ativadas ✓",
    notifBlocked:"Notificações bloqueadas — altere as configurações",
    notifNotSupported:"Notificações não suportadas neste navegador",
    notifActive:"Ativado — toque para testar",
    notifDenied:"Bloqueado — altere as configurações do navegador",
    notifPrompt:"Toque para permitir notificações",
    browserNotif:"Notificações do navegador",
    notifSound:"Som de notificação",
    notifPreview:"Mostrar prévia da mensagem",
    notifPreviewDesc:"Exibir o texto da mensagem na notificação",
    ringtoneLabel:"Toque de notificação", ringtoneTap:"Toque para pré-visualizar",
    newMessage:"Nova mensagem",
    statusPosted:"Status publicado — visível por 24 horas", statusRemoved:"Status removido",
    callEnded:"Chamada encerrada", missedCall:"Chamada perdida", missedCallFrom:"Chamada perdida de", callNotAnswered:"Chamada não atendida",
    sentPhoto:"Enviou uma foto", sentVideo:"Enviou um vídeo", sentVoice:"Enviou uma mensagem de voz", sentFile:"Enviou um arquivo",
    postedNewStatus:"Publicou um novo status", unreadMessage:"mensagem não lida", unreadMessages:"mensagens não lidas",
    darkTheme:"Tema escuro", currently:"Atualmente",
    enterSend:"Enter para enviar", enterSendDesc:"Caso contrário, Enter insere uma nova linha",
    autoplay:"Reprodução automática de vídeos",
    showOnline:"Mostrar status online", showOnlineDesc:"Permitir que outros vejam quando você está online",
    showLastSeen:"Mostrar última vez visto", showLastSeenDesc:"Mostrar quando você esteve ativo pela última vez",
    readReceipts:"Confirmações de leitura", readReceiptsDesc:"Mostrar duplo check ao ler mensagens",
    privacyNote:"As preferências de privacidade são armazenadas neste dispositivo.",
    browserStorage:"Armazenamento do navegador", clearCache:"Limpar cache local",
    clearCacheDesc:"Remove temas e configurações locais",
    storageNote:"As mensagens permanecem seguras na nuvem.",
    used:"usado de", available:"disponível",
    image:"Imagem", video:"Vídeo", file:"Arquivo / PDF",
    typeMessage:"Digite uma mensagem",
    today:"Hoje", yesterday:"Ontem",
    online:"online", typing:"digitando...", lastSeen:"visto por último",
    justNow:"agora mesmo", minAgo:"min", hAgo:"h",
    noMessages:"Sem mensagens — diga olá!",
    sendImage:"Enviar imagem", sendVideo:"Enviar vídeo", sendFile:"Enviar arquivo",
    uploading:"Enviando", uploadFailed:"Falha no envio",
    voiceMessage:"Mensagem de voz", stopRecording:"Parar gravação",
    micDenied:"Acesso ao microfone negado.",
    switchToLight:"Mudar para claro", switchToDark:"Mudar para escuro",
    lightTheme:"Tema claro", lightThemeOn:"Tema claro ativado", darkThemeOn:"Tema escuro ativado",
    profileTitle:"Perfil",
    accountSetting:"Conta", privacySetting:"Privacidade",
    privacySettingSub:"Status online, última vez visto, confirmações de leitura",
    chatsSetting:"Conversas", chatsSettingSub:"Tema, tecla de envio, reprodução automática",
    notificationsSetting:"Notificações", notificationsSettingSub:"Alertas do navegador, som, prévia",
    storageDataSetting:"Armazenamento e dados", storageDataSub:"Armazenamento, limpar cache",
    tapToCopyId:"Toque para copiar seu ID único", userIdCopied:"ID de usuário copiado",
    logOut:"Sair",
    profilePhotoUpdated:"Foto de perfil atualizada", couldNotUploadPhoto:"Não foi possível enviar a foto",
    profileSaved:"Perfil salvo", couldNotSaveProfile:"Não foi possível salvar o perfil",
    pleasePickImage:"Por favor escolha um arquivo de imagem", imageTooLarge:"A imagem deve ter menos de 5 MB",
    save:"Salvar", saving:"Salvando...", defaultBio:"Olá! Estou usando o Chatrazze.",
    recentCallHistory:"Histórico de chamadas recentes.",
    noCallsYet:"Sem chamadas ainda",
    noCallsDesc:"Chamadas de voz e vídeo aparecerão aqui após uma chamada.",
    callTypesLabel:"Tipos de chamada", incoming:"Recebida", outgoing:"Realizada", missed:"Perdida",
    callHistoryCleared:"Histórico de chamadas limpo", dAgo:"d",
    newChat:"Nova conversa", newGroup:"Novo grupo",
    searchChatsMessages:"Pesquisar conversas e mensagens",
    filterAll:"Todas", filterUnread:"Não lidas", filterFavorites:"Favoritos", filterGroups:"Grupos",
    noChatsFilter:"Nenhuma conversa corresponde ao filtro.", noChatsYet:"Sem conversas. Toque + para começar.",
    sayHi:"Diga olá", removeFavorite:"Remover dos favoritos", markFavorite:"Adicionar aos favoritos",
    searchByNameOrId:"Pesquisar por nome ou ID de usuário",
    searching:"Pesquisando...", noUsersFound:"Nenhum usuário encontrado.",
    groupNameLabel:"Nome do grupo", enterGroupName:"Digite o nome do grupo...",
    addMembersLabel:"Adicionar membros", searchUsersPlaceholder:"Pesquisar usuários...",
    creating:"Criando…", createGroupBtn:"Criar grupo",
    groupInfo:"Info do grupo", membersCount:"membros",
    messagesLabel:"Mensagens", photosLabel:"Fotos", videosLabel:"Vídeos",
    voiceLabel:"Voz", filesLabel:"Arquivos",
    moreActions:"Mais ações", viewAllMembers:"Ver todos os membros", showLessMembers:"Ver menos",
    addMember:"Adicionar membro", loadingMembers:"Carregando membros...",
    youSuffix:"(Você)", onlineCapital:"Online", offlineCapital:"Offline",
    noMediaShared:"Nenhuma mídia compartilhada.", noFilesShared:"Nenhum arquivo compartilhado.",
    leaveGroup:"Sair do grupo", leavingGroup:"Saindo...", leftGroup:"Você saiu do grupo.",
    searchByName:"Pesquisar por nome...",
    typeNameToFind:"Digite um nome para encontrar alguém.",
    notInGroup:"Nenhum usuário encontrado — ou já é membro.",
    adding:"Adicionando…", add:"Adicionar",
    contactInfo:"Info do contato", emailLabel:"E-mail", phoneLabel:"Telefone",
    voiceMessagesLabel:"Mensagens de voz", voiceMessagesCount:"mensagens de voz",
    voiceCallBtn:"Voz", videoCallBtn:"Vídeo",
    mediaTab:"Mídia", filesTab:"Arquivos",
    unblockUser:"Desbloquear", blockUser:"Bloquear",
    privacyPanelTitle:"Privacidade", storagePanelTitle:"Armazenamento",
    clearedCacheMsg:"itens removidos do cache", couldNotClearCache:"Não foi possível limpar o cache",
    fastModernMessaging:"Mensagens rápidas e modernas.",
    signIn:"Entrar", signUp:"Cadastrar",
    displayNamePlaceholder:"Nome de exibição", phoneOptionalPlaceholder:"Telefone (opcional)",
    emailPlaceholder:"E-mail", passwordPlaceholder:"Senha",
    pleaseWait:"Aguarde...", createAccount:"Criar conta",
    poweredBy:"Desenvolvido com Supabase. Suas mensagens são armazenadas em tempo real.",
    authFailed:"Falha na autenticação",
    callBack:"Retornar chamada",
    callingLabel:"Chamando...", connectingLabel:"Conectando...",
    incomingVideoCall:"Videochamada recebida", incomingVoiceCall:"Chamada de voz recebida",
    declineBtn:"Recusar", acceptBtn:"Aceitar",
    speakerBtn:"Alto-falante", muteBtn:"Silenciar", unmuteBtn:"Ativar som",
    endBtn:"Encerrar", cameraBtn:"Câmera",
    loadingDots:"Carregando...", members:"membros", group:"Grupo",
    addedToGroup:"adicionado ao grupo!",
    chatBgTitle:"Fundo do chat", chatBgDesc:"Escolha seu fundo",
    adminLabel:"Admin", editGroup:"Editar grupo", groupPhoto:"Foto do grupo",
    groupNameEdited:"Nome do grupo atualizado", groupPhotoUpdated:"Foto do grupo atualizada",
    addCaption:"Adicionar legenda...", storyText:"Texto", storyCamera:"Foto", tapCameraToUpload:"Toque para carregar",
    groupDescription:"Descrição do grupo", addGroupDesc:"Adicionar descrição", editDescription:"Editar descrição", descriptionHint:"Sobre o grupo...",
    inviteViaLink:"Convidar via link", qrCode:"Código QR", copyLink:"Copiar link", linkCopied:"Link copiado!",
    disappearingMsgs:"Mensagens temporárias", disappearOff:"Desativado", disappear24h:"24 horas", disappear7d:"7 dias", disappear90d:"90 dias",
    lockChat:"Bloquear conversa", lockChatDesc:"Exigir PIN para abrir", setPIN:"Definir PIN", enterPIN:"Inserir PIN",
    confirmPIN:"Confirmar PIN", pinSet:"PIN definido", pinRemoved:"PIN removido", wrongPIN:"PIN incorreto",
    muteNotifs:"Silenciar notificações", mute8h:"8 horas", mute1w:"1 semana", muteAlways:"Sempre",
    unmute:"Ativar som", mutedLabel:"Silenciado",
    encryptionInfo:"Criptografia", encryptTitle:"Criptografia de ponta a ponta",
    encryptDesc:"Mensagens e chamadas nesta conversa são protegidas com criptografia de ponta a ponta.",
    exportChat:"Exportar conversa", chatExported:"Conversa exportada",
    clearAllMsgs:"Apagar todas as mensagens", chatCleared:"Conversa apagada",
    reportGroup:"Denunciar grupo", reportSent:"Denúncia enviada",
    noResults:"Sem resultados", callMember:"Chamar membro",
    searchInChat:"Pesquisar na conversa",
    settingsSection:"Configurações", accountSection:"Conta", appearanceSection:"Aparência", helpSection:"Ajuda",
    inviteFriends:"Convidar amigos", starredMessages:"Mensagens favoritas", starredMessagesSub:"Conversas que você favoritou",
    broadcastMsg:"Mensagem em massa", broadcastMsgSub:"Envie para várias pessoas de uma vez",
    linkedDevicesLabel:"Dispositivos vinculados", linkedDevicesSub:"Sessões ativas na sua conta",
    helpFeedback:"Ajuda e comentários", helpFeedbackSub:"Contate o suporte ou envie comentários",
    shareBtn:"Compartilhar", inviteShareDesc:"Compartilhe o link com seus amigos para se conectar no Chatrazze",
    noStarredChats:"Sem conversas favoritas", noStarredChatsSub:"Pressione e segure uma conversa para favoritá-la",
    searchUserPlaceholder:"Buscar usuário…", nextBtn:"Próximo", selectedCount:"selecionado(s)",
    typeYourMessage:"Escreva sua mensagem…", goBack:"Voltar", personCount:"pessoa(s)",
    sentToPrefix:"Mensagem enviada para", couldNotSend:"Não foi possível enviar",
    activeSession:"Sessão ativa neste dispositivo", thisDeviceActive:"Este dispositivo · Ativo",
    lastActivity:"Última atividade:", devicesNote:"Chatrazze suporta uma sessão por vez. Entre de qualquer navegador e sua sessão sincroniza automaticamente.",
    bioLabel:"Bio", nameLabel:"Nome", linksLabel:"Links", addLinkBtn:"Adicionar link",
    editBtn:"Editar", cancel:"Cancelar", unknownBrowser:"Navegador desconhecido", unknownOS:"Sistema desconhecido",
    reply:"Responder", copyText:"Copiar texto", deleteMsg:"Apagar", replyingTo:"Respondendo a",
    msgCopied:"Copiado!", you:"Você", forwardMsg:"Encaminhar",
  },
  it: {
    status:"Stato", calls:"Chiamate", communities:"Comunità", chats:"Chat", profile:"Profilo",
    statusTitle:"Stato", statusSub:"Condividi momenti che scompaiono in 24h.",
    myStatus:"Il mio stato", tapToAdd:"Tocca per aggiungere stato",
    recentUpdates:"Aggiornamenti recenti", noUpdates:"Nessun aggiornamento recente",
    noUpdatesDesc:"Gli stati di altre persone appariranno qui.",
    removeStatus:"Rimuovi il mio stato", newStatus:"Nuovo stato",
    whatsOnMind:"A cosa stai pensando?", share:"Condividi",
    disappears:"Scompare in 24h", addImage:"Aggiungi immagine", addText:"Aggiungi testo", preview:"Anteprima",
    language:"Lingua",
    welcome:"Benvenuto su Chatrazze",
    welcomeSub:"Seleziona una conversazione o iniziane una nuova.",
    notifEnabled:"Notifiche attivate ✓",
    notifBlocked:"Notifiche bloccate — modifica le impostazioni",
    notifNotSupported:"Notifiche non supportate in questo browser",
    notifActive:"Attivato — tocca per testare",
    notifDenied:"Bloccato — modifica le impostazioni del browser",
    notifPrompt:"Tocca per consentire le notifiche",
    browserNotif:"Notifiche del browser",
    notifSound:"Suono di notifica",
    notifPreview:"Mostra anteprima messaggio",
    notifPreviewDesc:"Visualizza il testo del messaggio nella notifica",
    ringtoneLabel:"Suoneria notifica", ringtoneTap:"Tocca per anteprima",
    newMessage:"Nuovo messaggio",
    statusPosted:"Stato pubblicato — visibile per 24 ore", statusRemoved:"Stato rimosso",
    callEnded:"Chiamata terminata", missedCall:"Chiamata persa", missedCallFrom:"Chiamata persa da", callNotAnswered:"Chiamata senza risposta",
    sentPhoto:"Ha inviato una foto", sentVideo:"Ha inviato un video", sentVoice:"Ha inviato un messaggio vocale", sentFile:"Ha inviato un file",
    postedNewStatus:"Ha pubblicato un nuovo stato", unreadMessage:"messaggio non letto", unreadMessages:"messaggi non letti",
    darkTheme:"Tema scuro", currently:"Attualmente",
    enterSend:"Invio per inviare", enterSendDesc:"Altrimenti Invio inserisce una nuova riga",
    autoplay:"Riproduzione automatica video",
    showOnline:"Mostra stato online", showOnlineDesc:"Permettere agli altri di vedere quando sei online",
    showLastSeen:"Mostra ultimo accesso", showLastSeenDesc:"Mostra quando sei stato attivo l'ultima volta",
    readReceipts:"Conferme di lettura", readReceiptsDesc:"Mostra doppia spunta quando leggi i messaggi",
    privacyNote:"Le preferenze sulla privacy sono memorizzate su questo dispositivo.",
    browserStorage:"Archiviazione browser", clearCache:"Svuota cache locale",
    clearCacheDesc:"Rimuove temi e impostazioni locali",
    storageNote:"I messaggi rimangono al sicuro nel cloud.",
    used:"usato di", available:"disponibile",
    image:"Immagine", video:"Video", file:"File / PDF",
    typeMessage:"Scrivi un messaggio",
    today:"Oggi", yesterday:"Ieri",
    online:"online", typing:"sta scrivendo...", lastSeen:"visto l'ultima volta",
    justNow:"proprio ora", minAgo:"min", hAgo:"h",
    noMessages:"Nessun messaggio — di' ciao!",
    sendImage:"Invia immagine", sendVideo:"Invia video", sendFile:"Invia file",
    uploading:"Caricamento", uploadFailed:"Caricamento fallito",
    voiceMessage:"Messaggio vocale", stopRecording:"Interrompi registrazione",
    micDenied:"Accesso al microfono negato.",
    switchToLight:"Passa al chiaro", switchToDark:"Passa allo scuro",
    lightTheme:"Tema chiaro", lightThemeOn:"Tema chiaro attivato", darkThemeOn:"Tema scuro attivato",
    profileTitle:"Profilo",
    accountSetting:"Account", privacySetting:"Privacy",
    privacySettingSub:"Stato online, ultimo accesso, conferme di lettura",
    chatsSetting:"Chat", chatsSettingSub:"Tema, tasto invio, riproduzione automatica",
    notificationsSetting:"Notifiche", notificationsSettingSub:"Avvisi browser, suono, anteprima",
    storageDataSetting:"Archiviazione e dati", storageDataSub:"Archiviazione browser, svuota cache",
    tapToCopyId:"Tocca per copiare il tuo ID univoco", userIdCopied:"ID utente copiato",
    logOut:"Disconnettersi",
    profilePhotoUpdated:"Foto profilo aggiornata", couldNotUploadPhoto:"Impossibile caricare la foto",
    profileSaved:"Profilo salvato", couldNotSaveProfile:"Impossibile salvare il profilo",
    pleasePickImage:"Scegli un file immagine", imageTooLarge:"L'immagine deve essere inferiore a 5 MB",
    save:"Salva", saving:"Salvataggio...", defaultBio:"Ciao! Sto usando Chatrazze.",
    recentCallHistory:"Cronologia chiamate recenti.",
    noCallsYet:"Nessuna chiamata ancora",
    noCallsDesc:"Le chiamate vocali e video appariranno qui dopo una chiamata.",
    callTypesLabel:"Tipi di chiamata", incoming:"In arrivo", outgoing:"In uscita", missed:"Persa",
    callHistoryCleared:"Cronologia chiamate eliminata", dAgo:"g",
    newChat:"Nuova chat", newGroup:"Nuovo gruppo",
    searchChatsMessages:"Cerca chat e messaggi",
    filterAll:"Tutti", filterUnread:"Non letti", filterFavorites:"Preferiti", filterGroups:"Gruppi",
    noChatsFilter:"Nessuna chat corrisponde al filtro.", noChatsYet:"Nessuna chat. Tocca + per iniziare.",
    sayHi:"Di' ciao", removeFavorite:"Rimuovi dai preferiti", markFavorite:"Aggiungi ai preferiti",
    searchByNameOrId:"Cerca per nome o ID utente",
    searching:"Ricerca...", noUsersFound:"Nessun utente trovato.",
    groupNameLabel:"Nome del gruppo", enterGroupName:"Inserisci il nome del gruppo...",
    addMembersLabel:"Aggiungi membri", searchUsersPlaceholder:"Cerca utenti...",
    creating:"Creazione…", createGroupBtn:"Crea gruppo",
    groupInfo:"Info gruppo", membersCount:"membri",
    messagesLabel:"Messaggi", photosLabel:"Foto", videosLabel:"Video",
    voiceLabel:"Vocali", filesLabel:"File",
    moreActions:"Altre azioni", viewAllMembers:"Visualizza tutti i membri", showLessMembers:"Mostra meno",
    addMember:"Aggiungi membro", loadingMembers:"Caricamento membri...",
    youSuffix:"(Tu)", onlineCapital:"Online", offlineCapital:"Offline",
    noMediaShared:"Nessun media condiviso.", noFilesShared:"Nessun file condiviso.",
    leaveGroup:"Abbandona gruppo", leavingGroup:"Uscita...", leftGroup:"Hai abbandonato il gruppo.",
    searchByName:"Cerca per nome...",
    typeNameToFind:"Digita un nome per trovare qualcuno.",
    notInGroup:"Nessun utente trovato — o già membro del gruppo.",
    adding:"Aggiunta…", add:"Aggiungi",
    contactInfo:"Info contatto", emailLabel:"E-mail", phoneLabel:"Telefono",
    voiceMessagesLabel:"Messaggi vocali", voiceMessagesCount:"messaggi vocali",
    voiceCallBtn:"Voce", videoCallBtn:"Video",
    mediaTab:"Media", filesTab:"File",
    unblockUser:"Sblocca", blockUser:"Blocca",
    privacyPanelTitle:"Privacy", storagePanelTitle:"Archiviazione",
    clearedCacheMsg:"elementi rimossi dalla cache", couldNotClearCache:"Impossibile svuotare la cache",
    fastModernMessaging:"Messaggistica rapida e moderna.",
    signIn:"Accedi", signUp:"Registrati",
    displayNamePlaceholder:"Nome visualizzato", phoneOptionalPlaceholder:"Telefono (opzionale)",
    emailPlaceholder:"E-mail", passwordPlaceholder:"Password",
    pleaseWait:"Attendere prego...", createAccount:"Crea account",
    poweredBy:"Sviluppato con Supabase. I tuoi messaggi sono archiviati in tempo reale.",
    authFailed:"Autenticazione fallita",
    callBack:"Richiama",
    callingLabel:"Chiamata in corso...", connectingLabel:"Connessione...",
    incomingVideoCall:"Videochiamata in arrivo", incomingVoiceCall:"Chiamata vocale in arrivo",
    declineBtn:"Rifiuta", acceptBtn:"Accetta",
    speakerBtn:"Altoparlante", muteBtn:"Silenzia", unmuteBtn:"Attiva audio",
    endBtn:"Termina", cameraBtn:"Fotocamera",
    loadingDots:"Caricamento...", members:"membri", group:"Gruppo",
    addedToGroup:"aggiunto al gruppo!",
    chatBgTitle:"Sfondo chat", chatBgDesc:"Scegli il tuo sfondo",
    adminLabel:"Admin", editGroup:"Modifica gruppo", groupPhoto:"Foto del gruppo",
    groupNameEdited:"Nome del gruppo aggiornato", groupPhotoUpdated:"Foto del gruppo aggiornata",
    addCaption:"Aggiungi didascalia...", storyText:"Testo", storyCamera:"Foto", tapCameraToUpload:"Caricare foto",
    groupDescription:"Descrizione del gruppo", addGroupDesc:"Aggiungi descrizione", editDescription:"Modifica descrizione", descriptionHint:"Informazioni sul gruppo...",
    inviteViaLink:"Invita tramite link", qrCode:"Codice QR", copyLink:"Copia link", linkCopied:"Link copiato!",
    disappearingMsgs:"Messaggi temporanei", disappearOff:"Disattivato", disappear24h:"24 ore", disappear7d:"7 giorni", disappear90d:"90 giorni",
    lockChat:"Blocca chat", lockChatDesc:"Richiedi PIN per aprire", setPIN:"Imposta PIN", enterPIN:"Inserisci PIN",
    confirmPIN:"Conferma PIN", pinSet:"PIN impostato", pinRemoved:"PIN rimosso", wrongPIN:"PIN errato",
    muteNotifs:"Silenzia notifiche", mute8h:"8 ore", mute1w:"1 settimana", muteAlways:"Sempre",
    unmute:"Riattiva audio", mutedLabel:"Silenziato",
    encryptionInfo:"Crittografia", encryptTitle:"Crittografia end-to-end",
    encryptDesc:"I messaggi e le chiamate in questa chat sono protetti con crittografia end-to-end.",
    exportChat:"Esporta chat", chatExported:"Chat esportata",
    clearAllMsgs:"Cancella tutti i messaggi", chatCleared:"Chat svuotata",
    reportGroup:"Segnala gruppo", reportSent:"Segnalazione inviata",
    noResults:"Nessun risultato", callMember:"Chiama membro",
    searchInChat:"Cerca nella chat",
    settingsSection:"Impostazioni", accountSection:"Account", appearanceSection:"Aspetto", helpSection:"Aiuto",
    inviteFriends:"Invita amici", starredMessages:"Messaggi preferiti", starredMessagesSub:"Chat che hai segnato",
    broadcastMsg:"Messaggio di massa", broadcastMsgSub:"Invia a più persone contemporaneamente",
    linkedDevicesLabel:"Dispositivi collegati", linkedDevicesSub:"Sessioni attive sul tuo account",
    helpFeedback:"Aiuto e feedback", helpFeedbackSub:"Contatta il supporto o invia feedback",
    shareBtn:"Condividi", inviteShareDesc:"Condividi il link con i tuoi amici per connettersi su Chatrazze",
    noStarredChats:"Nessuna chat preferita", noStarredChatsSub:"Tieni premuta una chat per aggiungerla ai preferiti",
    searchUserPlaceholder:"Cerca utente…", nextBtn:"Avanti", selectedCount:"selezionato/i",
    typeYourMessage:"Scrivi il tuo messaggio…", goBack:"Indietro", personCount:"persona/e",
    sentToPrefix:"Messaggio inviato a", couldNotSend:"Impossibile inviare",
    activeSession:"Sessione attiva su questo dispositivo", thisDeviceActive:"Questo dispositivo · Attivo",
    lastActivity:"Ultima attività:", devicesNote:"Chatrazze supporta una sessione alla volta. Accedi da qualsiasi browser e la tua sessione si sincronizza automaticamente.",
    bioLabel:"Bio", nameLabel:"Nome", linksLabel:"Link", addLinkBtn:"Aggiungi link",
    editBtn:"Modifica", cancel:"Annulla", unknownBrowser:"Browser sconosciuto", unknownOS:"Sistema sconosciuto",
    reply:"Rispondi", copyText:"Copia testo", deleteMsg:"Elimina", replyingTo:"In risposta a",
    msgCopied:"Copiato!", you:"Tu", forwardMsg:"Inoltra",
  },
  tr: {
    status:"Durum", calls:"Aramalar", communities:"Topluluklar", chats:"Sohbetler", profile:"Profil",
    statusTitle:"Durum", statusSub:"24 saatte kaybolan anlar paylaşın.",
    myStatus:"Durumum", tapToAdd:"Durum eklemek için dokunun",
    recentUpdates:"Son güncellemeler", noUpdates:"Son güncelleme yok",
    noUpdatesDesc:"Diğer kişilerin durum güncellemeleri burada görünecek.",
    removeStatus:"Durumumu kaldır", newStatus:"Yeni durum",
    whatsOnMind:"Ne düşünüyorsunuz?", share:"Paylaş",
    disappears:"24 saatte kayboluyor", addImage:"Resim ekle", addText:"Metin ekle", preview:"Önizleme",
    language:"Dil",
    welcome:"Chatrazze'ye hoş geldiniz",
    welcomeSub:"Bir konuşma seçin veya yeni bir konuşma başlatın.",
    notifEnabled:"Bildirimler etkinleştirildi ✓",
    notifBlocked:"Bildirimler engellendi — ayarları değiştirin",
    notifNotSupported:"Bu tarayıcıda bildirimler desteklenmiyor",
    notifActive:"Etkin — test etmek için dokunun",
    notifDenied:"Engellendi — tarayıcı ayarlarını değiştirin",
    notifPrompt:"Bildirimlere izin vermek için dokunun",
    browserNotif:"Tarayıcı bildirimleri",
    notifSound:"Bildirim sesi",
    notifPreview:"Mesaj önizlemesini göster",
    notifPreviewDesc:"Bildirimde mesaj metnini göster",
    ringtoneLabel:"Bildirim zil sesi", ringtoneTap:"Önizlemek için dokun",
    newMessage:"Yeni mesaj",
    statusPosted:"Durum yayınlandı — 24 saat görünür", statusRemoved:"Durum kaldırıldı",
    callEnded:"Çağrı sona erdi", missedCall:"Cevapsız çağrı", missedCallFrom:"Cevapsız çağrı:", callNotAnswered:"Çağrı cevaplanmadı",
    sentPhoto:"Bir fotoğraf gönderdi", sentVideo:"Bir video gönderdi", sentVoice:"Sesli mesaj gönderdi", sentFile:"Bir dosya gönderdi",
    postedNewStatus:"Yeni bir durum paylaştı", unreadMessage:"okunmamış mesaj", unreadMessages:"okunmamış mesaj",
    darkTheme:"Koyu tema", currently:"Şu anda",
    enterSend:"Göndermek için Enter", enterSendDesc:"Aksi takdirde Enter yeni satır ekler",
    autoplay:"Videoları otomatik oynat",
    showOnline:"Çevrimiçi durumu göster", showOnlineDesc:"Başkalarının sizi görmesine izin verin",
    showLastSeen:"Son görülmeyi göster", showLastSeenDesc:"En son ne zaman aktif olduğunuzu göster",
    readReceipts:"Okundu bildirimleri", readReceiptsDesc:"Mesajları okuduğunuzda çift tik göster",
    privacyNote:"Gizlilik tercihleri bu cihazda saklanır.",
    browserStorage:"Tarayıcı depolama", clearCache:"Yerel önbelleği temizle",
    clearCacheDesc:"Temaları ve yerel ayarları kaldırır",
    storageNote:"Mesajlar bulutta güvende kalır.",
    used:"kullanıldı", available:"mevcut",
    image:"Resim", video:"Video", file:"Dosya / PDF",
    typeMessage:"Mesaj yazın",
    today:"Bugün", yesterday:"Dün",
    online:"çevrimiçi", typing:"yazıyor...", lastSeen:"son görülme",
    justNow:"az önce", minAgo:"dk", hAgo:"s",
    noMessages:"Henüz mesaj yok — merhaba deyin!",
    sendImage:"Resim gönder", sendVideo:"Video gönder", sendFile:"Dosya gönder",
    uploading:"Yükleniyor", uploadFailed:"Yükleme başarısız",
    voiceMessage:"Sesli mesaj", stopRecording:"Kaydı durdur",
    micDenied:"Mikrofon erişimi reddedildi.",
    switchToLight:"Açık temaya geç", switchToDark:"Koyu temaya geç",
    lightTheme:"Açık tema", lightThemeOn:"Açık tema etkinleştirildi", darkThemeOn:"Koyu tema etkinleştirildi",
    profileTitle:"Profil",
    accountSetting:"Hesap", privacySetting:"Gizlilik",
    privacySettingSub:"Çevrimiçi durum, son görülme, okundu bildirimleri",
    chatsSetting:"Sohbetler", chatsSettingSub:"Tema, gönder tuşu, otomatik oynat",
    notificationsSetting:"Bildirimler", notificationsSettingSub:"Tarayıcı bildirimleri, ses, önizleme",
    storageDataSetting:"Depolama ve veriler", storageDataSub:"Tarayıcı depolama, önbellek temizle",
    tapToCopyId:"Benzersiz kimliğinizi kopyalamak için dokunun", userIdCopied:"Kullanıcı kimliği kopyalandı",
    logOut:"Çıkış yap",
    profilePhotoUpdated:"Profil fotoğrafı güncellendi", couldNotUploadPhoto:"Fotoğraf yüklenemedi",
    profileSaved:"Profil kaydedildi", couldNotSaveProfile:"Profil kaydedilemedi",
    pleasePickImage:"Lütfen bir resim dosyası seçin", imageTooLarge:"Resim 5 MB'tan küçük olmalıdır",
    save:"Kaydet", saving:"Kaydediliyor...", defaultBio:"Merhaba! Chatrazze kullanıyorum.",
    recentCallHistory:"Son arama geçmişi.",
    noCallsYet:"Henüz arama yok",
    noCallsDesc:"Sesli ve görüntülü aramalar bir arama yapıldıktan sonra burada görünecek.",
    callTypesLabel:"Arama türleri", incoming:"Gelen", outgoing:"Giden", missed:"Cevapsız",
    callHistoryCleared:"Arama geçmişi temizlendi", dAgo:"g",
    newChat:"Yeni sohbet", newGroup:"Yeni grup",
    searchChatsMessages:"Sohbetlerde ve mesajlarda ara",
    filterAll:"Tümü", filterUnread:"Okunmamış", filterFavorites:"Favoriler", filterGroups:"Gruplar",
    noChatsFilter:"Filtreyle eşleşen sohbet yok.", noChatsYet:"Sohbet yok. Başlamak için + tuşuna basın.",
    sayHi:"Merhaba de", removeFavorite:"Favorilerden çıkar", markFavorite:"Favorilere ekle",
    searchByNameOrId:"Ada veya kullanıcı kimliğine göre ara",
    searching:"Aranıyor...", noUsersFound:"Kullanıcı bulunamadı.",
    groupNameLabel:"Grup adı", enterGroupName:"Grup adını girin...",
    addMembersLabel:"Üye ekle", searchUsersPlaceholder:"Kullanıcı ara...",
    creating:"Oluşturuluyor…", createGroupBtn:"Grup oluştur",
    groupInfo:"Grup bilgisi", membersCount:"üye",
    messagesLabel:"Mesajlar", photosLabel:"Fotoğraflar", videosLabel:"Videolar",
    voiceLabel:"Sesli", filesLabel:"Dosyalar",
    moreActions:"Daha fazla işlem", viewAllMembers:"Tüm üyeleri görüntüle", showLessMembers:"Daha az göster",
    addMember:"Üye ekle", loadingMembers:"Üyeler yükleniyor...",
    youSuffix:"(Sen)", onlineCapital:"Çevrimiçi", offlineCapital:"Çevrimdışı",
    noMediaShared:"Henüz medya paylaşılmadı.", noFilesShared:"Henüz dosya paylaşılmadı.",
    leaveGroup:"Gruptan ayrıl", leavingGroup:"Ayrılıyor...", leftGroup:"Gruptan ayrıldınız.",
    searchByName:"Ada göre ara...",
    typeNameToFind:"Birini eklemek için ad yazın.",
    notInGroup:"Kullanıcı bulunamadı — veya zaten grup üyesi.",
    adding:"Ekleniyor…", add:"Ekle",
    contactInfo:"Kişi bilgisi", emailLabel:"E-posta", phoneLabel:"Telefon",
    voiceMessagesLabel:"Sesli mesajlar", voiceMessagesCount:"sesli mesaj",
    voiceCallBtn:"Ses", videoCallBtn:"Video",
    mediaTab:"Medya", filesTab:"Dosyalar",
    unblockUser:"Engeli kaldır", blockUser:"Engelle",
    privacyPanelTitle:"Gizlilik", storagePanelTitle:"Depolama",
    clearedCacheMsg:"önbellek öğesi temizlendi", couldNotClearCache:"Önbellek temizlenemedi",
    fastModernMessaging:"Hızlı, modern mesajlaşma.",
    signIn:"Giriş yap", signUp:"Kayıt ol",
    displayNamePlaceholder:"Görünen ad", phoneOptionalPlaceholder:"Telefon (isteğe bağlı)",
    emailPlaceholder:"E-posta", passwordPlaceholder:"Şifre",
    pleaseWait:"Lütfen bekleyin...", createAccount:"Hesap oluştur",
    poweredBy:"Supabase ile güçlendirildi. Mesajlarınız gerçek zamanlı olarak saklanır.",
    authFailed:"Kimlik doğrulama başarısız",
    callBack:"Geri ara",
    callingLabel:"Aranıyor...", connectingLabel:"Bağlanıyor...",
    incomingVideoCall:"Gelen görüntülü arama", incomingVoiceCall:"Gelen sesli arama",
    declineBtn:"Reddet", acceptBtn:"Kabul et",
    speakerBtn:"Hoparlör", muteBtn:"Sesi kes", unmuteBtn:"Sesi aç",
    endBtn:"Bitir", cameraBtn:"Kamera",
    loadingDots:"Yükleniyor...", members:"üye", group:"Grup",
    addedToGroup:"gruba eklendi!",
    chatBgTitle:"Sohbet Arka Planı", chatBgDesc:"Arka planınızı seçin",
    adminLabel:"Yönetici", editGroup:"Grubu düzenle", groupPhoto:"Grup fotoğrafı",
    groupNameEdited:"Grup adı güncellendi", groupPhotoUpdated:"Grup fotoğrafı güncellendi",
    addCaption:"Açıklama ekle...", storyText:"Metin", storyCamera:"Fotoğraf", tapCameraToUpload:"Fotoğraf yükle",
    groupDescription:"Grup açıklaması", addGroupDesc:"Açıklama ekle", editDescription:"Açıklamayı düzenle", descriptionHint:"Grup hakkında...",
    inviteViaLink:"Bağlantıyla davet et", qrCode:"QR kod", copyLink:"Bağlantıyı kopyala", linkCopied:"Bağlantı kopyalandı!",
    disappearingMsgs:"Kaybolan mesajlar", disappearOff:"Kapalı", disappear24h:"24 saat", disappear7d:"7 gün", disappear90d:"90 gün",
    lockChat:"Sohbeti kilitle", lockChatDesc:"Açmak için PIN gerekli", setPIN:"PIN ayarla", enterPIN:"PIN girin",
    confirmPIN:"PIN'i onayla", pinSet:"PIN ayarlandı", pinRemoved:"PIN kaldırıldı", wrongPIN:"Yanlış PIN",
    muteNotifs:"Bildirimleri sessize al", mute8h:"8 saat", mute1w:"1 hafta", muteAlways:"Her zaman",
    unmute:"Sesi aç", mutedLabel:"Sessize alındı",
    encryptionInfo:"Şifreleme", encryptTitle:"Uçtan uca şifreli",
    encryptDesc:"Bu sohbetteki mesajlar ve aramalar uçtan uca şifreleme ile korunmaktadır.",
    exportChat:"Sohbeti dışa aktar", chatExported:"Sohbet dışa aktarıldı",
    clearAllMsgs:"Tüm mesajları sil", chatCleared:"Sohbet temizlendi",
    reportGroup:"Grubu bildir", reportSent:"Bildirim gönderildi",
    noResults:"Sonuç yok", callMember:"Üyeyi ara",
    searchInChat:"Sohbette ara",
    settingsSection:"Ayarlar", accountSection:"Hesap", appearanceSection:"Görünüm", helpSection:"Yardım",
    inviteFriends:"Arkadaşları davet et", starredMessages:"Yıldızlı mesajlar", starredMessagesSub:"Yıldızladığın sohbetler",
    broadcastMsg:"Toplu mesaj", broadcastMsgSub:"Aynı anda birden fazla kişiye gönder",
    linkedDevicesLabel:"Bağlı cihazlar", linkedDevicesSub:"Hesabındaki aktif oturumlar",
    helpFeedback:"Yardım & Geri bildirim", helpFeedbackSub:"Destek ile iletişime geç veya geri bildirim gönder",
    shareBtn:"Paylaş", inviteShareDesc:"Bağlantıyı arkadaşlarınla paylaş ve Chatrazze'de buluşun",
    noStarredChats:"Yıldızlı sohbet yok", noStarredChatsSub:"Bir sohbete uzun bas ve yıldızla",
    searchUserPlaceholder:"Kullanıcı ara…", nextBtn:"İleri", selectedCount:"seçili",
    typeYourMessage:"Mesajınızı yazın…", goBack:"Geri", personCount:"kişi",
    sentToPrefix:"Mesaj gönderildi", couldNotSend:"Gönderilemedi",
    activeSession:"Bu cihazdaki aktif oturum", thisDeviceActive:"Bu cihaz · Aktif",
    lastActivity:"Son aktivite:", devicesNote:"Chatrazze aynı anda bir oturumu destekler. Herhangi bir tarayıcıdan giriş yap ve oturumun otomatik senkronize olur.",
    bioLabel:"Bio", nameLabel:"Ad", linksLabel:"Bağlantılar", addLinkBtn:"Bağlantı ekle",
    editBtn:"Düzenle", cancel:"İptal", unknownBrowser:"Bilinmeyen tarayıcı", unknownOS:"Bilinmeyen sistem",
    reply:"Yanıtla", copyText:"Metni kopyala", deleteMsg:"Sil", replyingTo:"Yanıtlanıyor:",
    msgCopied:"Kopyalandı!", you:"Sen", forwardMsg:"İlet",
  },
} as const;

export type TKey = keyof typeof T.en;

function getSavedLang(): Lang {
  try {
    const saved = localStorage.getItem("chatrazze:lang");
    if (saved && (LANG_LIST.map(l => l.code) as string[]).includes(saved)) return saved as Lang;
  } catch {}
  return "en";
}

interface LangCtxType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TKey) => string;
  dir: "rtl" | "ltr";
}

const LangCtx = createContext<LangCtxType>({
  lang: "en", setLang: () => {}, t: (k) => k, dir: "ltr",
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(getSavedLang);

  const langMeta = LANG_LIST.find(l => l.code === lang)!;
  const dir = langMeta.dir;

  const setLang = (l: Lang) => {
    setLangState(l);
    try { localStorage.setItem("chatrazze:lang", l); } catch {}
  };

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
  }, [lang, dir]);

  const t = (key: TKey): string => {
    const table = T[lang] as Record<string, string>;
    return table[key] ?? (T.en as Record<string, string>)[key] ?? key;
  };

  return <LangCtx.Provider value={{ lang, setLang, t, dir }}>{children}</LangCtx.Provider>;
}

export function useLang() { return useContext(LangCtx); }
